// ─── Chamber Boost — Seed Data ───────────────────────────────────────────────
// Used by: app/services/chamber-boost/page.tsx (member deal browse experience)

export interface Deal {
  id: string
  title: string
  titleAr: string
  vendor: string
  vendorAr: string
  vendorLogo: string
  category: DealCategory
  categoryAr: string
  dealType: 'UNLIMITED' | 'LIMITED'
  description: string
  descriptionAr: string
  offerSummary: string
  offerSummaryAr: string
  discountValue: string
  discountValueAr: string
  originalValue?: string
  conditions: string[]
  conditionsAr: string[]
  validUntil: string
  availableSlots?: number
  claimedSlots?: number
  isFeatured: boolean
  isNew: boolean
  tags: string[]
  tagsAr: string[]
  vendorUrl: string
  redemptionInstructions: string
  redemptionInstructionsAr: string
}

export type DealCategory =
  | 'Technology'
  | 'Travel & Transport'
  | 'Office & Workspace'
  | 'Logistics'
  | 'Marketing & Media'
  | 'Finance & Banking'
  | 'HR & Productivity'
  | 'Cloud Services'

export const categoriesAr: Record<string, string> = {
  'Technology': 'التكنولوجيا',
  'Travel & Transport': 'السفر والنقل',
  'Office & Workspace': 'المكاتب ومساحات العمل',
  'Logistics': 'الخدمات اللوجستية',
  'Marketing & Media': 'التسويق والإعلام',
  'Finance & Banking': 'التمويل والبنوك',
  'HR & Productivity': 'الموارد البشرية والإنتاجية',
  'Cloud Services': 'الخدمات السحابية',
}

export const categoryColors: Record<string, string> = {
  'Technology': 'bg-cyan-100 dark:bg-cyan-500/20 text-cyan-800 dark:text-cyan-300 border-cyan-200 dark:border-cyan-500/30',
  'Travel & Transport': 'bg-sky-100 dark:bg-sky-500/20 text-sky-800 dark:text-sky-300 border-sky-200 dark:border-sky-500/30',
  'Office & Workspace': 'bg-violet-100 dark:bg-violet-500/20 text-violet-800 dark:text-violet-300 border-violet-200 dark:border-violet-500/30',
  'Logistics': 'bg-indigo-100 dark:bg-indigo-500/20 text-indigo-800 dark:text-indigo-300 border-indigo-200 dark:border-indigo-500/30',
  'Marketing & Media': 'bg-pink-100 dark:bg-pink-500/20 text-pink-800 dark:text-pink-300 border-pink-200 dark:border-pink-500/30',
  'Finance & Banking': 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-800 dark:text-emerald-300 border-emerald-200 dark:border-emerald-500/30',
  'HR & Productivity': 'bg-teal-100 dark:bg-teal-500/20 text-teal-800 dark:text-teal-300 border-teal-200 dark:border-teal-500/30',
  'Cloud Services': 'bg-blue-100 dark:bg-blue-500/20 text-blue-800 dark:text-blue-300 border-blue-200 dark:border-blue-500/30',
}

export const dealTypeColors: Record<string, string> = {
  'UNLIMITED': 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-800 dark:text-emerald-300 border-emerald-200 dark:border-emerald-500/30',
  'LIMITED': 'bg-amber-100 dark:bg-amber-500/20 text-amber-800 dark:text-amber-300 border-amber-200 dark:border-amber-500/30',
}

export const DEALS: Deal[] = [
  {
    id: 'cb-001',
    title: 'Dell Business Hardware Program',
    titleAr: 'برنامج ديل لأجهزة الأعمال',
    vendor: 'Dell',
    vendorAr: 'ديل',
    vendorLogo: 'DL',
    category: 'Technology',
    categoryAr: 'التكنولوجيا',
    dealType: 'UNLIMITED',
    description: 'Exclusive pricing on Dell business laptops, desktops, and workstations for ADCCI members. Includes extended warranty options and priority tech support for enterprise purchases.',
    descriptionAr: 'أسعار حصرية على أجهزة الكمبيوتر المحمولة وأجهزة سطح المكتب ومحطات العمل من ديل لأعضاء الغرفة. تشمل خيارات الضمان الممتد والدعم الفني ذو الأولوية للمشتريات المؤسسية.',
    offerSummary: '20% off all Dell hardware for ADCCI members',
    offerSummaryAr: 'خصم 20% على جميع أجهزة ديل لأعضاء الغرفة',
    discountValue: '20%',
    discountValueAr: '٢٠٪',
    originalValue: 'AED 5,000+',
    conditions: ['Valid for new purchases only', 'Minimum order AED 2,000', 'Cannot combine with other Dell promotions'],
    conditionsAr: ['صالح للمشتريات الجديدة فقط', 'الحد الأدنى للطلب 2,000 درهم', 'لا يمكن دمجه مع عروض ديل الأخرى'],
    validUntil: '2026-12-31',
    isFeatured: true,
    isNew: false,
    tags: ['Hardware', 'Laptops', 'Workstations', 'IT'],
    tagsAr: ['أجهزة', 'لابتوب', 'محطات عمل', 'تكنولوجيا المعلومات'],
    vendorUrl: 'https://dell.com/adcci',
    redemptionInstructions: 'Use the voucher code at checkout on dell.com/ae or contact your Dell account manager and mention your ADCCI membership.',
    redemptionInstructionsAr: 'استخدم رمز القسيمة عند الدفع على dell.com/ae أو تواصل مع مدير حساب ديل واذكر عضويتك في الغرفة.',
  },
  {
    id: 'cb-002',
    title: 'Etihad Business Travel Rewards',
    titleAr: 'مكافآت سفر الأعمال من الاتحاد',
    vendor: 'Etihad',
    vendorAr: 'الاتحاد للطيران',
    vendorLogo: 'EY',
    category: 'Travel & Transport',
    categoryAr: 'السفر والنقل',
    dealType: 'LIMITED',
    description: 'Premium business travel package with Etihad Airways. Includes priority check-in, lounge access, and bonus Etihad Guest Miles on all bookings made through ADCCI. Limited to 50 corporate accounts.',
    descriptionAr: 'حزمة سفر أعمال متميزة مع الاتحاد للطيران. تشمل تسجيل الوصول ذو الأولوية ودخول الصالات وأميال إضافية على جميع الحجوزات عبر الغرفة. محدودة بـ 50 حساباً مؤسسياً.',
    offerSummary: 'Up to AED 500 off per business class booking',
    offerSummaryAr: 'خصم يصل إلى 500 درهم لكل حجز درجة أعمال',
    discountValue: 'AED 500',
    discountValueAr: '٥٠٠ درهم',
    originalValue: 'AED 8,500/flight',
    conditions: ['Minimum 2 bookings per quarter', 'Business class only', 'Subject to availability'],
    conditionsAr: ['حجزان كحد أدنى في كل ربع سنة', 'درجة الأعمال فقط', 'حسب التوفر'],
    validUntil: '2026-09-30',
    availableSlots: 50,
    claimedSlots: 18,
    isFeatured: true,
    isNew: true,
    tags: ['Flights', 'Business Travel', 'Miles', 'Lounge'],
    tagsAr: ['رحلات', 'سفر الأعمال', 'أميال', 'صالة'],
    vendorUrl: 'https://etihad.com/adcci',
    redemptionInstructions: 'Once approved, you will receive a corporate booking code. Use it on etihad.com or through your travel agent.',
    redemptionInstructionsAr: 'بعد الموافقة ستحصل على رمز حجز مؤسسي. استخدمه على etihad.com أو عبر وكيل السفر.',
  },
  {
    id: 'cb-003',
    title: 'Google Workspace for Business',
    titleAr: 'جوجل وركسبيس للأعمال',
    vendor: 'Google',
    vendorAr: 'جوجل',
    vendorLogo: 'GL',
    category: 'Cloud Services',
    categoryAr: 'الخدمات السحابية',
    dealType: 'UNLIMITED',
    description: 'Get Google Workspace Business Standard at a discounted rate for your entire team. Includes Gmail, Drive, Meet, and all productivity tools with enhanced storage and security.',
    descriptionAr: 'احصل على Google Workspace بسعر مخفض لفريقك بالكامل. يشمل Gmail و Drive و Meet وجميع أدوات الإنتاجية مع تخزين محسّن وأمان متقدم.',
    offerSummary: '3 months free on annual Google Workspace subscription',
    offerSummaryAr: '3 أشهر مجانية على اشتراك Google Workspace السنوي',
    discountValue: '3 months free',
    discountValueAr: '٣ أشهر مجاناً',
    originalValue: 'AED 2,500/yr',
    conditions: ['New subscriptions only', 'Minimum 5 users', 'Annual billing required'],
    conditionsAr: ['اشتراكات جديدة فقط', 'الحد الأدنى 5 مستخدمين', 'فوترة سنوية مطلوبة'],
    validUntil: '2026-11-30',
    isFeatured: false,
    isNew: false,
    tags: ['Cloud', 'Email', 'Collaboration', 'SaaS'],
    tagsAr: ['سحابي', 'بريد إلكتروني', 'تعاون', 'خدمات سحابية'],
    vendorUrl: 'https://workspace.google.com/adcci',
    redemptionInstructions: 'Use the voucher code when setting up your Google Workspace account at workspace.google.com. Code must be applied during the first billing cycle.',
    redemptionInstructionsAr: 'استخدم رمز القسيمة عند إعداد حساب Google Workspace على workspace.google.com. يجب تطبيق الرمز خلال دورة الفوترة الأولى.',
  },
  {
    id: 'cb-004',
    title: 'Microsoft 365 Business Premium',
    titleAr: 'مايكروسوفت 365 بريميوم للأعمال',
    vendor: 'Microsoft',
    vendorAr: 'مايكروسوفت',
    vendorLogo: 'MS',
    category: 'Technology',
    categoryAr: 'التكنولوجيا',
    dealType: 'LIMITED',
    description: 'Microsoft 365 Business Premium with advanced cybersecurity features, Copilot AI assistant, and Teams Premium included. Special pricing tier exclusively for ADCCI member companies.',
    descriptionAr: 'مايكروسوفت 365 بريميوم مع ميزات الأمن السيبراني المتقدمة ومساعد Copilot الذكي و Teams Premium. مستوى تسعير خاص حصرياً لشركات أعضاء الغرفة.',
    offerSummary: '30% off Microsoft 365 Business Premium for first year',
    offerSummaryAr: 'خصم 30% على Microsoft 365 بريميوم للسنة الأولى',
    discountValue: '30%',
    discountValueAr: '٣٠٪',
    originalValue: 'AED 1,200/user/yr',
    conditions: ['Minimum 10 licenses', 'First year only — renews at standard rate', 'Requires Microsoft partner setup'],
    conditionsAr: ['الحد الأدنى 10 تراخيص', 'السنة الأولى فقط — يُجدد بالسعر العادي', 'يتطلب إعداد شريك مايكروسوفت'],
    validUntil: '2026-08-31',
    availableSlots: 40,
    claimedSlots: 12,
    isFeatured: true,
    isNew: false,
    tags: ['Office', 'AI', 'Copilot', 'Security', 'Teams'],
    tagsAr: ['أوفيس', 'ذكاء اصطناعي', 'كوبايلوت', 'أمان', 'تيمز'],
    vendorUrl: 'https://microsoft.com/adcci',
    redemptionInstructions: 'Once approved, a Microsoft partner representative will contact you to set up licensing and onboarding within 5 business days.',
    redemptionInstructionsAr: 'بعد الموافقة سيتواصل معك ممثل شريك مايكروسوفت لإعداد التراخيص والتأهيل خلال 5 أيام عمل.',
  },
  {
    id: 'cb-005',
    title: 'Careem Business Corporate Transport',
    titleAr: 'كريم للأعمال — النقل المؤسسي',
    vendor: 'Careem Business',
    vendorAr: 'كريم للأعمال',
    vendorLogo: 'CB',
    category: 'Travel & Transport',
    categoryAr: 'السفر والنقل',
    dealType: 'UNLIMITED',
    description: 'Centralized corporate ride management with Careem Business. Track employee trips, set spending limits, and receive consolidated monthly invoices with ADCCI-exclusive rates.',
    descriptionAr: 'إدارة مركزية لرحلات الشركات مع كريم للأعمال. تتبع رحلات الموظفين وحدد حدود الإنفاق واحصل على فواتير شهرية موحدة بأسعار حصرية للغرفة.',
    offerSummary: '15% off all Careem Business rides',
    offerSummaryAr: 'خصم 15% على جميع رحلات كريم للأعمال',
    discountValue: '15%',
    discountValueAr: '١٥٪',
    conditions: ['Minimum 3 employees enrolled', 'Valid in UAE only', 'Monthly billing minimum AED 500'],
    conditionsAr: ['الحد الأدنى 3 موظفين مسجلين', 'صالح في الإمارات فقط', 'الحد الأدنى للفوترة الشهرية 500 درهم'],
    validUntil: '2027-03-31',
    isFeatured: false,
    isNew: false,
    tags: ['Transport', 'Rides', 'Corporate', 'Mobility'],
    tagsAr: ['نقل', 'رحلات', 'مؤسسي', 'تنقل'],
    vendorUrl: 'https://business.careem.com',
    redemptionInstructions: 'Sign up at business.careem.com with your ADCCI voucher code. Your corporate account will be activated within 24 hours.',
    redemptionInstructionsAr: 'سجل على business.careem.com باستخدام رمز القسيمة. سيتم تفعيل حسابك المؤسسي خلال 24 ساعة.',
  },
  {
    id: 'cb-006',
    title: 'Zoom Enterprise Communication Suite',
    titleAr: 'حزمة زووم للاتصالات المؤسسية',
    vendor: 'Zoom',
    vendorAr: 'زووم',
    vendorLogo: 'ZM',
    category: 'HR & Productivity',
    categoryAr: 'الموارد البشرية والإنتاجية',
    dealType: 'UNLIMITED',
    description: 'Zoom Business plan with unlimited meeting duration, cloud recording, and AI companion features. Perfect for remote teams and hybrid work environments.',
    descriptionAr: 'خطة Zoom Business مع مدة اجتماعات غير محدودة وتسجيل سحابي وميزات الرفيق الذكي. مثالية للفرق البعيدة وبيئات العمل الهجينة.',
    offerSummary: '25% off Zoom Business annual plan',
    offerSummaryAr: 'خصم 25% على الخطة السنوية لـ Zoom Business',
    discountValue: '25%',
    discountValueAr: '٢٥٪',
    originalValue: 'AED 900/user/yr',
    conditions: ['Minimum 10 licenses', 'Annual commitment required', 'New customers only'],
    conditionsAr: ['الحد الأدنى 10 تراخيص', 'التزام سنوي مطلوب', 'عملاء جدد فقط'],
    validUntil: '2026-10-31',
    isFeatured: false,
    isNew: true,
    tags: ['Video', 'Meetings', 'Collaboration', 'Remote Work'],
    tagsAr: ['فيديو', 'اجتماعات', 'تعاون', 'عمل عن بعد'],
    vendorUrl: 'https://zoom.us/adcci',
    redemptionInstructions: 'Use the voucher code at zoom.us/pricing when selecting the Business plan. Code auto-applies the ADCCI discount.',
    redemptionInstructionsAr: 'استخدم رمز القسيمة على zoom.us/pricing عند اختيار خطة Business. يطبق الرمز خصم الغرفة تلقائياً.',
  },
  {
    id: 'cb-007',
    title: 'Salesforce CRM for SMEs',
    titleAr: 'نظام Salesforce لإدارة العملاء للشركات الصغيرة',
    vendor: 'Salesforce',
    vendorAr: 'سيلز فورس',
    vendorLogo: 'SF',
    category: 'Technology',
    categoryAr: 'التكنولوجيا',
    dealType: 'LIMITED',
    description: 'Salesforce Starter Suite designed for SMEs entering the CRM space. Includes sales, service, and marketing tools in one platform with ADCCI-exclusive onboarding support.',
    descriptionAr: 'حزمة Salesforce Starter المصممة للشركات الصغيرة والمتوسطة. تشمل أدوات المبيعات والخدمة والتسويق في منصة واحدة مع دعم تأهيل حصري للغرفة.',
    offerSummary: '40% off Salesforce Starter for first 6 months',
    offerSummaryAr: 'خصم 40% على Salesforce Starter لأول 6 أشهر',
    discountValue: '40%',
    discountValueAr: '٤٠٪',
    originalValue: 'AED 3,600/yr',
    conditions: ['Companies with fewer than 200 employees', '6-month promotional pricing', 'Renews at standard rate'],
    conditionsAr: ['شركات أقل من 200 موظف', 'تسعير ترويجي لمدة 6 أشهر', 'يُجدد بالسعر العادي'],
    validUntil: '2026-07-31',
    availableSlots: 30,
    claimedSlots: 22,
    isFeatured: false,
    isNew: false,
    tags: ['CRM', 'Sales', 'Marketing', 'Automation'],
    tagsAr: ['إدارة علاقات العملاء', 'مبيعات', 'تسويق', 'أتمتة'],
    vendorUrl: 'https://salesforce.com/adcci',
    redemptionInstructions: 'After approval, a Salesforce representative will schedule an onboarding call to set up your organization within 3 business days.',
    redemptionInstructionsAr: 'بعد الموافقة سيتواصل ممثل Salesforce لجدولة مكالمة تأهيل وإعداد مؤسستك خلال 3 أيام عمل.',
  },
  {
    id: 'cb-008',
    title: 'WeWork Flexible Office Solutions',
    titleAr: 'حلول المكاتب المرنة من وي وورك',
    vendor: 'WeWork',
    vendorAr: 'وي وورك',
    vendorLogo: 'WW',
    category: 'Office & Workspace',
    categoryAr: 'المكاتب ومساحات العمل',
    dealType: 'LIMITED',
    description: 'Flexible workspace memberships at WeWork locations across Abu Dhabi and Dubai. Includes hot desks, dedicated desks, and private office options with all amenities included.',
    descriptionAr: 'عضويات مساحات عمل مرنة في مواقع WeWork في أبوظبي ودبي. تشمل المكاتب المشتركة والمكاتب المخصصة وخيارات المكاتب الخاصة مع جميع المرافق.',
    offerSummary: 'AED 500 off monthly WeWork membership',
    offerSummaryAr: 'خصم 500 درهم على عضوية WeWork الشهرية',
    discountValue: 'AED 500/mo',
    discountValueAr: '٥٠٠ درهم/شهر',
    originalValue: 'AED 3,000/mo',
    conditions: ['Minimum 3-month commitment', 'Available at Abu Dhabi & Dubai locations', 'Subject to desk availability'],
    conditionsAr: ['التزام 3 أشهر كحد أدنى', 'متاح في مواقع أبوظبي ودبي', 'حسب توفر المكاتب'],
    validUntil: '2026-12-31',
    availableSlots: 25,
    claimedSlots: 9,
    isFeatured: true,
    isNew: false,
    tags: ['Office', 'Coworking', 'Flexible', 'Workspace'],
    tagsAr: ['مكتب', 'عمل مشترك', 'مرن', 'مساحة عمل'],
    vendorUrl: 'https://wework.com/adcci',
    redemptionInstructions: 'After approval, visit your preferred WeWork location with your voucher code and member ID to activate your discounted membership.',
    redemptionInstructionsAr: 'بعد الموافقة قم بزيارة موقع WeWork المفضل لديك مع رمز القسيمة وهوية العضوية لتفعيل عضويتك المخفضة.',
  },
  {
    id: 'cb-009',
    title: 'DHL Express Business Shipping',
    titleAr: 'شحن الأعمال السريع من دي إتش إل',
    vendor: 'DHL Express',
    vendorAr: 'دي إتش إل إكسبرس',
    vendorLogo: 'DH',
    category: 'Logistics',
    categoryAr: 'الخدمات اللوجستية',
    dealType: 'UNLIMITED',
    description: 'Preferential shipping rates for ADCCI members on all international DHL Express shipments. Includes dedicated account management and priority customs clearance for UAE businesses.',
    descriptionAr: 'أسعار شحن تفضيلية لأعضاء الغرفة على جميع شحنات DHL Express الدولية. تشمل إدارة حساب مخصصة وتخليص جمركي ذو أولوية للشركات الإماراتية.',
    offerSummary: 'Up to 35% off international shipping rates',
    offerSummaryAr: 'خصم يصل إلى 35% على أسعار الشحن الدولي',
    discountValue: '35%',
    discountValueAr: '٣٥٪',
    conditions: ['Volume-based discount tiers', 'International shipments only', 'Excludes hazardous goods'],
    conditionsAr: ['مستويات خصم حسب الحجم', 'شحنات دولية فقط', 'يستثني البضائع الخطرة'],
    validUntil: '2027-06-30',
    isFeatured: false,
    isNew: false,
    tags: ['Shipping', 'Express', 'International', 'Logistics'],
    tagsAr: ['شحن', 'سريع', 'دولي', 'لوجستيات'],
    vendorUrl: 'https://dhl.com/ae/adcci',
    redemptionInstructions: 'Register your DHL business account with the voucher code at mydhl.express.dhl. Discount applies automatically on all subsequent shipments.',
    redemptionInstructionsAr: 'سجل حساب DHL التجاري باستخدام رمز القسيمة على mydhl.express.dhl. يُطبق الخصم تلقائياً على جميع الشحنات اللاحقة.',
  },
  {
    id: 'cb-010',
    title: 'Mastercard Business Solutions',
    titleAr: 'حلول ماستركارد للأعمال',
    vendor: 'Mastercard Business',
    vendorAr: 'ماستركارد للأعمال',
    vendorLogo: 'MC',
    category: 'Finance & Banking',
    categoryAr: 'التمويل والبنوك',
    dealType: 'LIMITED',
    description: 'Corporate card program with Mastercard offering cashback on business expenses, expense management tools, and travel insurance. Exclusive tier for ADCCI Premium and Elite Plus members.',
    descriptionAr: 'برنامج بطاقات مؤسسية مع ماستركارد يقدم استرداد نقدي على نفقات الأعمال وأدوات إدارة المصاريف وتأمين السفر. فئة حصرية لأعضاء الغرفة المميزين والنخبة بلس.',
    offerSummary: '2% cashback on all business expenses with no annual fee',
    offerSummaryAr: 'استرداد نقدي 2% على جميع نفقات الأعمال بدون رسوم سنوية',
    discountValue: '2% cashback',
    discountValueAr: 'استرداد ٢٪',
    conditions: ['Premium or Elite Plus members only', 'Minimum monthly spend AED 5,000', 'Subject to credit approval'],
    conditionsAr: ['أعضاء مميزون أو النخبة بلس فقط', 'الحد الأدنى للإنفاق الشهري 5,000 درهم', 'خاضع لموافقة الائتمان'],
    validUntil: '2026-12-31',
    availableSlots: 100,
    claimedSlots: 34,
    isFeatured: false,
    isNew: false,
    tags: ['Finance', 'Cards', 'Cashback', 'Expense Management'],
    tagsAr: ['تمويل', 'بطاقات', 'استرداد نقدي', 'إدارة المصاريف'],
    vendorUrl: 'https://mastercard.ae/adcci',
    redemptionInstructions: 'After approval, your application will be forwarded to the issuing bank. A representative will contact you within 5 business days to complete the setup.',
    redemptionInstructionsAr: 'بعد الموافقة سيتم تحويل طلبك إلى البنك المُصدر. سيتواصل معك ممثل خلال 5 أيام عمل لإتمام الإعداد.',
  },
  {
    id: 'cb-011',
    title: 'Noon Business Procurement',
    titleAr: 'نون للأعمال — المشتريات المؤسسية',
    vendor: 'Noon Business',
    vendorAr: 'نون للأعمال',
    vendorLogo: 'NN',
    category: 'Office & Workspace',
    categoryAr: 'المكاتب ومساحات العمل',
    dealType: 'UNLIMITED',
    description: 'Business procurement portal on Noon with bulk ordering, invoice billing, and dedicated account support. Access to office supplies, electronics, and pantry items at wholesale rates.',
    descriptionAr: 'بوابة مشتريات أعمال على نون مع طلبات بالجملة وفوترة وحساب دعم مخصص. وصول إلى مستلزمات المكاتب والإلكترونيات وأغراض المطبخ بأسعار الجملة.',
    offerSummary: '10% off all orders + free next-day delivery',
    offerSummaryAr: 'خصم 10% على جميع الطلبات + توصيل مجاني في اليوم التالي',
    discountValue: '10%',
    discountValueAr: '١٠٪',
    conditions: ['Minimum order AED 200', 'Delivery within UAE only', 'Business account required'],
    conditionsAr: ['الحد الأدنى للطلب 200 درهم', 'التوصيل داخل الإمارات فقط', 'حساب أعمال مطلوب'],
    validUntil: '2027-01-31',
    isFeatured: false,
    isNew: false,
    tags: ['Procurement', 'Office Supplies', 'E-commerce', 'Bulk'],
    tagsAr: ['مشتريات', 'مستلزمات مكتبية', 'تجارة إلكترونية', 'بالجملة'],
    vendorUrl: 'https://business.noon.com',
    redemptionInstructions: 'Create a Noon Business account and enter the voucher code in the promo section. Discount auto-applies to all eligible orders.',
    redemptionInstructionsAr: 'أنشئ حساب نون للأعمال وأدخل رمز القسيمة في قسم العروض. يُطبق الخصم تلقائياً على جميع الطلبات المؤهلة.',
  },
  {
    id: 'cb-012',
    title: 'Aramex Business Logistics Suite',
    titleAr: 'حزمة أرامكس اللوجستية للأعمال',
    vendor: 'Aramex',
    vendorAr: 'أرامكس',
    vendorLogo: 'AX',
    category: 'Logistics',
    categoryAr: 'الخدمات اللوجستية',
    dealType: 'LIMITED',
    description: 'End-to-end logistics solutions including domestic delivery, warehousing, and e-commerce fulfillment. Special pricing for ADCCI members with dedicated account management.',
    descriptionAr: 'حلول لوجستية شاملة تشمل التوصيل المحلي والتخزين وخدمات التجارة الإلكترونية. أسعار خاصة لأعضاء الغرفة مع إدارة حساب مخصصة.',
    offerSummary: '20% off domestic delivery + free warehousing setup',
    offerSummaryAr: 'خصم 20% على التوصيل المحلي + إعداد تخزين مجاني',
    discountValue: '20%',
    discountValueAr: '٢٠٪',
    conditions: ['Minimum 100 shipments/month', '6-month contract required', 'UAE operations only'],
    conditionsAr: ['الحد الأدنى 100 شحنة/شهر', 'عقد 6 أشهر مطلوب', 'عمليات الإمارات فقط'],
    validUntil: '2026-09-30',
    availableSlots: 20,
    claimedSlots: 14,
    isFeatured: false,
    isNew: false,
    tags: ['Logistics', 'Delivery', 'Warehousing', 'E-commerce'],
    tagsAr: ['لوجستيات', 'توصيل', 'تخزين', 'تجارة إلكترونية'],
    vendorUrl: 'https://aramex.com/adcci',
    redemptionInstructions: 'After approval, an Aramex account manager will schedule a consultation to assess your logistics needs and set up your account.',
    redemptionInstructionsAr: 'بعد الموافقة سيقوم مدير حساب أرامكس بجدولة استشارة لتقييم احتياجاتك اللوجستية وإعداد حسابك.',
  },
  {
    id: 'cb-013',
    title: 'AWS Cloud Credits Program',
    titleAr: 'برنامج أرصدة AWS السحابية',
    vendor: 'AWS',
    vendorAr: 'خدمات أمازون السحابية',
    vendorLogo: 'AW',
    category: 'Cloud Services',
    categoryAr: 'الخدمات السحابية',
    dealType: 'LIMITED',
    description: 'Up to AED 10,000 in AWS cloud credits for ADCCI member companies launching new workloads or migrating to the cloud. Includes 3 months of AWS Business Support.',
    descriptionAr: 'ما يصل إلى 10,000 درهم من أرصدة AWS السحابية لشركات أعضاء الغرفة التي تطلق أحمال عمل جديدة أو تنتقل إلى السحابة. يشمل 3 أشهر من دعم AWS للأعمال.',
    offerSummary: 'AED 10,000 cloud credits + 3 months Business Support',
    offerSummaryAr: '10,000 درهم أرصدة سحابية + 3 أشهر دعم أعمال',
    discountValue: 'AED 10,000',
    discountValueAr: '١٠,٠٠٠ درهم',
    conditions: ['New AWS accounts or new workloads only', 'Credits valid for 12 months', 'Must complete AWS Business Plan'],
    conditionsAr: ['حسابات AWS جديدة أو أحمال عمل جديدة فقط', 'الأرصدة صالحة لمدة 12 شهراً', 'يجب إكمال خطة عمل AWS'],
    validUntil: '2026-06-30',
    availableSlots: 15,
    claimedSlots: 11,
    isFeatured: false,
    isNew: true,
    tags: ['Cloud', 'AWS', 'Credits', 'Infrastructure'],
    tagsAr: ['سحابي', 'أمازون', 'أرصدة', 'بنية تحتية'],
    vendorUrl: 'https://aws.amazon.com/adcci',
    redemptionInstructions: 'After approval, you will receive an AWS activation link. Complete the Business Plan form and credits will be applied to your account within 48 hours.',
    redemptionInstructionsAr: 'بعد الموافقة ستحصل على رابط تفعيل AWS. أكمل نموذج خطة العمل وسيتم إضافة الأرصدة لحسابك خلال 48 ساعة.',
  },
  {
    id: 'cb-014',
    title: 'Cisco Networking Essentials',
    titleAr: 'أساسيات شبكات سيسكو',
    vendor: 'Cisco',
    vendorAr: 'سيسكو',
    vendorLogo: 'CS',
    category: 'Technology',
    categoryAr: 'التكنولوجيا',
    dealType: 'UNLIMITED',
    description: 'Discounted Cisco Meraki cloud-managed networking equipment and licenses. Includes switches, access points, and security appliances with simplified dashboard management.',
    descriptionAr: 'خصم على معدات وتراخيص شبكات Cisco Meraki المُدارة سحابياً. تشمل المحولات ونقاط الوصول وأجهزة الأمان مع إدارة لوحة تحكم مبسطة.',
    offerSummary: '15% off Cisco Meraki hardware + free 1-year license',
    offerSummaryAr: 'خصم 15% على أجهزة Cisco Meraki + ترخيص مجاني لمدة سنة',
    discountValue: '15%',
    discountValueAr: '١٥٪',
    conditions: ['Minimum 5 devices', 'Standard support included', 'Valid for Meraki product line only'],
    conditionsAr: ['الحد الأدنى 5 أجهزة', 'الدعم الأساسي مشمول', 'صالح لخط منتجات Meraki فقط'],
    validUntil: '2026-12-31',
    isFeatured: false,
    isNew: false,
    tags: ['Networking', 'Security', 'Wi-Fi', 'Infrastructure'],
    tagsAr: ['شبكات', 'أمان', 'واي فاي', 'بنية تحتية'],
    vendorUrl: 'https://meraki.cisco.com/adcci',
    redemptionInstructions: 'Use the voucher code when placing your order through a Cisco authorized reseller. Quote your ADCCI membership number for verification.',
    redemptionInstructionsAr: 'استخدم رمز القسيمة عند تقديم طلبك عبر موزع سيسكو المعتمد. اذكر رقم عضويتك في الغرفة للتحقق.',
  },
  {
    id: 'cb-015',
    title: 'Oracle Cloud Infrastructure Starter',
    titleAr: 'البنية السحابية من أوراكل — باقة البداية',
    vendor: 'Oracle',
    vendorAr: 'أوراكل',
    vendorLogo: 'OC',
    category: 'Cloud Services',
    categoryAr: 'الخدمات السحابية',
    dealType: 'LIMITED',
    description: 'Oracle Cloud Infrastructure credits and free database migration assistance for ADCCI member companies. Includes Oracle Autonomous Database and OCI Compute resources.',
    descriptionAr: 'أرصدة البنية السحابية من أوراكل ومساعدة مجانية في ترحيل قواعد البيانات لشركات أعضاء الغرفة. تشمل قاعدة بيانات Oracle Autonomous وموارد OCI Compute.',
    offerSummary: 'AED 7,500 OCI credits + free database migration',
    offerSummaryAr: '7,500 درهم أرصدة OCI + ترحيل قاعدة بيانات مجاني',
    discountValue: 'AED 7,500',
    discountValueAr: '٧,٥٠٠ درهم',
    conditions: ['New OCI accounts only', 'Credits valid for 90 days', 'Migration support limited to 1 database'],
    conditionsAr: ['حسابات OCI جديدة فقط', 'الأرصدة صالحة لمدة 90 يوماً', 'دعم الترحيل محدود بقاعدة بيانات واحدة'],
    validUntil: '2026-08-31',
    availableSlots: 20,
    claimedSlots: 5,
    isFeatured: false,
    isNew: false,
    tags: ['Cloud', 'Database', 'OCI', 'Migration'],
    tagsAr: ['سحابي', 'قاعدة بيانات', 'أوراكل', 'ترحيل'],
    vendorUrl: 'https://oracle.com/cloud/adcci',
    redemptionInstructions: 'After approval, Oracle will provide a Universal Credits code. Apply it at cloud.oracle.com to activate your credits and schedule database migration.',
    redemptionInstructionsAr: 'بعد الموافقة ستوفر أوراكل رمز أرصدة شامل. طبقه على cloud.oracle.com لتفعيل أرصدتك وجدولة ترحيل قاعدة البيانات.',
  },
  {
    id: 'cb-016',
    title: 'HubSpot Marketing & Sales Hub',
    titleAr: 'منصة HubSpot للتسويق والمبيعات',
    vendor: 'HubSpot',
    vendorAr: 'هب سبوت',
    vendorLogo: 'HS',
    category: 'Marketing & Media',
    categoryAr: 'التسويق والإعلام',
    dealType: 'UNLIMITED',
    description: 'All-in-one marketing automation and CRM platform. Includes email marketing, social media management, lead tracking, and analytics dashboard for data-driven growth.',
    descriptionAr: 'منصة شاملة لأتمتة التسويق وإدارة العملاء. تشمل التسويق بالبريد الإلكتروني وإدارة وسائل التواصل وتتبع العملاء ولوحة تحليلات للنمو القائم على البيانات.',
    offerSummary: '20% off HubSpot Professional plan for 12 months',
    offerSummaryAr: 'خصم 20% على خطة HubSpot Professional لمدة 12 شهراً',
    discountValue: '20%',
    discountValueAr: '٢٠٪',
    originalValue: 'AED 4,800/yr',
    conditions: ['New HubSpot customers only', 'Professional plan or above', 'Annual billing required'],
    conditionsAr: ['عملاء HubSpot جدد فقط', 'خطة Professional أو أعلى', 'فوترة سنوية مطلوبة'],
    validUntil: '2026-11-30',
    isFeatured: false,
    isNew: false,
    tags: ['Marketing', 'CRM', 'Automation', 'Analytics'],
    tagsAr: ['تسويق', 'إدارة علاقات العملاء', 'أتمتة', 'تحليلات'],
    vendorUrl: 'https://hubspot.com/adcci',
    redemptionInstructions: 'Visit hubspot.com/adcci and apply the voucher code during checkout. The discount will reflect on your first annual invoice.',
    redemptionInstructionsAr: 'قم بزيارة hubspot.com/adcci وطبق رمز القسيمة عند الدفع. سيظهر الخصم على فاتورتك السنوية الأولى.',
  },
  {
    id: 'cb-017',
    title: 'LinkedIn Talent Solutions',
    titleAr: 'حلول المواهب من لينكد إن',
    vendor: 'LinkedIn',
    vendorAr: 'لينكد إن',
    vendorLogo: 'LI',
    category: 'HR & Productivity',
    categoryAr: 'الموارد البشرية والإنتاجية',
    dealType: 'LIMITED',
    description: 'LinkedIn Recruiter Lite and LinkedIn Learning licenses for ADCCI member companies. Find and hire top talent while upskilling your existing workforce through 16,000+ courses.',
    descriptionAr: 'تراخيص LinkedIn Recruiter Lite و LinkedIn Learning لشركات أعضاء الغرفة. اعثر على أفضل المواهب ووظفهم مع تطوير مهارات فريقك عبر أكثر من 16,000 دورة تدريبية.',
    offerSummary: '25% off LinkedIn Recruiter + free Learning licenses',
    offerSummaryAr: 'خصم 25% على LinkedIn Recruiter + تراخيص Learning مجانية',
    discountValue: '25%',
    discountValueAr: '٢٥٪',
    conditions: ['Annual subscription required', 'Up to 5 free Learning licenses per company', 'Cannot combine with other LinkedIn offers'],
    conditionsAr: ['اشتراك سنوي مطلوب', 'حتى 5 تراخيص Learning مجانية لكل شركة', 'لا يمكن دمجه مع عروض لينكد إن الأخرى'],
    validUntil: '2026-10-31',
    availableSlots: 35,
    claimedSlots: 8,
    isFeatured: false,
    isNew: false,
    tags: ['Recruitment', 'HR', 'Learning', 'Talent'],
    tagsAr: ['توظيف', 'موارد بشرية', 'تعلم', 'مواهب'],
    vendorUrl: 'https://business.linkedin.com/adcci',
    redemptionInstructions: 'After approval, a LinkedIn Talent Solutions representative will contact you to set up your Recruiter Lite account and distribute Learning licenses.',
    redemptionInstructionsAr: 'بعد الموافقة سيتواصل ممثل حلول المواهب من لينكد إن لإعداد حساب Recruiter Lite وتوزيع تراخيص Learning.',
  },
  {
    id: 'cb-018',
    title: 'FedEx SME Express Shipping',
    titleAr: 'شحن فيديكس السريع للشركات الصغيرة',
    vendor: 'FedEx',
    vendorAr: 'فيديكس',
    vendorLogo: 'FX',
    category: 'Logistics',
    categoryAr: 'الخدمات اللوجستية',
    dealType: 'UNLIMITED',
    description: 'Preferential rates for ADCCI member SMEs on FedEx Express international shipping. Includes package tracking, customs brokerage support, and flexible pickup scheduling.',
    descriptionAr: 'أسعار تفضيلية للشركات الصغيرة والمتوسطة أعضاء الغرفة على شحنات فيديكس الدولية السريعة. تشمل تتبع الشحنات ودعم التخليص الجمركي وجدولة استلام مرنة.',
    offerSummary: '30% off FedEx International Express for SMEs',
    offerSummaryAr: 'خصم 30% على شحنات فيديكس الدولية السريعة للشركات الصغيرة',
    discountValue: '30%',
    discountValueAr: '٣٠٪',
    conditions: ['Companies under 100 employees', 'International shipments only', 'Minimum 10 shipments/month'],
    conditionsAr: ['شركات أقل من 100 موظف', 'شحنات دولية فقط', 'الحد الأدنى 10 شحنات/شهر'],
    validUntil: '2027-03-31',
    isFeatured: false,
    isNew: false,
    tags: ['Shipping', 'Express', 'International', 'SME'],
    tagsAr: ['شحن', 'سريع', 'دولي', 'شركات صغيرة'],
    vendorUrl: 'https://fedex.com/ae/adcci',
    redemptionInstructions: 'Open a FedEx business account at fedex.com/ae and enter the voucher code in the corporate discount field. Rates apply to all subsequent shipments.',
    redemptionInstructionsAr: 'افتح حساب أعمال فيديكس على fedex.com/ae وأدخل رمز القسيمة في حقل الخصم المؤسسي. تُطبق الأسعار على جميع الشحنات اللاحقة.',
  },
]
