export interface Report {
  id: string
  title: string
  titleAr: string
  institution: string
  institutionAr: string
  category: string
  categoryAr: string
  publishedDate: string
  description: string
  descriptionAr: string
  tags: string[]
  tagsAr: string[]
  fileSize: string
  pageCount: number
  downloadUrl: string
  thumbnailUrl: string
  isFeatured: boolean
  language: 'English' | 'Arabic' | 'Bilingual'
}

export const institutionColors: Record<string, { bg: string; text: string }> = {
  IMF: { bg: 'bg-blue-600', text: 'text-white' },
  McKinsey: { bg: 'bg-sky-700', text: 'text-white' },
  'UAE Central Bank': { bg: 'bg-emerald-700', text: 'text-white' },
  PwC: { bg: 'bg-amber-600', text: 'text-white' },
  Deloitte: { bg: 'bg-green-600', text: 'text-white' },
  'Oxford Economics': { bg: 'bg-indigo-600', text: 'text-white' },
  'World Bank': { bg: 'bg-cyan-700', text: 'text-white' },
  'S&P Global': { bg: 'bg-red-600', text: 'text-white' },
  EY: { bg: 'bg-yellow-500', text: 'text-gray-900' },
  KPMG: { bg: 'bg-blue-800', text: 'text-white' },
  'Abu Dhabi Investment Office': { bg: 'bg-teal-700', text: 'text-white' },
  'Boston Consulting Group': { bg: 'bg-green-700', text: 'text-white' },
  'Moody\'s Analytics': { bg: 'bg-purple-700', text: 'text-white' },
}

export const categories = [
  'Macroeconomics',
  'Real Estate',
  'Energy',
  'Technology',
  'Trade & Investment',
  'SME & Entrepreneurship',
]

export const categoriesAr: Record<string, string> = {
  'Macroeconomics': 'الاقتصاد الكلي',
  'Real Estate': 'العقارات',
  'Energy': 'الطاقة',
  'Technology': 'التكنولوجيا',
  'Trade & Investment': 'التجارة والاستثمار',
  'SME & Entrepreneurship': 'المنشآت الصغيرة وريادة الأعمال',
}

export const institutions = [
  'IMF',
  'McKinsey',
  'UAE Central Bank',
  'PwC',
  'Deloitte',
  'Oxford Economics',
  'World Bank',
  'S&P Global',
  'EY',
  'KPMG',
  'Abu Dhabi Investment Office',
  'Boston Consulting Group',
  'Moody\'s Analytics',
]

export const reports: Report[] = [
  {
    id: 'rpt-001',
    title: 'UAE Economic Outlook 2026: Growth Drivers & Fiscal Strategy',
    titleAr: 'النظرة الاقتصادية للإمارات 2026: محركات النمو والاستراتيجية المالية',
    institution: 'IMF',
    institutionAr: 'صندوق النقد الدولي',
    category: 'Macroeconomics',
    categoryAr: 'الاقتصاد الكلي',
    publishedDate: '2026-01-15',
    description: 'Comprehensive analysis of UAE GDP growth projections, non-oil sector expansion, and fiscal consolidation strategies. Includes detailed forecasts for inflation, trade balance, and public debt sustainability through 2028.',
    descriptionAr: 'تحليل شامل لتوقعات نمو الناتج المحلي الإجمالي للإمارات، وتوسع القطاع غير النفطي، واستراتيجيات التوحيد المالي. يتضمن توقعات مفصلة للتضخم والميزان التجاري واستدامة الدين العام حتى 2028.',
    tags: ['GDP', 'fiscal policy', 'non-oil economy', 'inflation'],
    tagsAr: ['الناتج المحلي', 'السياسة المالية', 'الاقتصاد غير النفطي', 'التضخم'],
    fileSize: '3.2 MB',
    pageCount: 48,
    downloadUrl: '/mock/reports/uae-economic-outlook-2026.pdf',
    thumbnailUrl: '',
    isFeatured: true,
    language: 'English',
  },
  {
    id: 'rpt-002',
    title: 'Abu Dhabi Real Estate Market Intelligence Report Q4 2025',
    titleAr: 'تقرير استخبارات سوق العقارات في أبوظبي - الربع الرابع 2025',
    institution: 'PwC',
    institutionAr: 'برايس ووترهاوس كوبرز',
    category: 'Real Estate',
    categoryAr: 'العقارات',
    publishedDate: '2026-01-08',
    description: 'Quarterly market intelligence covering residential, commercial, and industrial real estate trends in Abu Dhabi. Features pricing analytics, demand-supply dynamics, and emerging investment hotspots across key districts.',
    descriptionAr: 'استخبارات سوقية فصلية تغطي اتجاهات العقارات السكنية والتجارية والصناعية في أبوظبي. تتضمن تحليلات الأسعار وديناميكيات العرض والطلب ونقاط الاستثمار الناشئة.',
    tags: ['real estate', 'property market', 'investment', 'Abu Dhabi'],
    tagsAr: ['العقارات', 'سوق العقارات', 'الاستثمار', 'أبوظبي'],
    fileSize: '2.8 MB',
    pageCount: 36,
    downloadUrl: '/mock/reports/ad-real-estate-q4-2025.pdf',
    thumbnailUrl: '',
    isFeatured: true,
    language: 'Bilingual',
  },
  {
    id: 'rpt-003',
    title: 'Energy Transition Roadmap: UAE Net Zero 2050 Progress Report',
    titleAr: 'خريطة طريق التحول في الطاقة: تقرير تقدم الإمارات نحو صافي الصفر 2050',
    institution: 'McKinsey',
    institutionAr: 'ماكنزي',
    category: 'Energy',
    categoryAr: 'الطاقة',
    publishedDate: '2025-12-20',
    description: 'Strategic assessment of UAE progress toward its Net Zero 2050 target. Covers renewable energy capacity growth, hydrogen economy development, carbon capture initiatives, and the role of nuclear energy in the national energy mix.',
    descriptionAr: 'تقييم استراتيجي لتقدم الإمارات نحو هدف صافي الصفر 2050. يغطي نمو قدرة الطاقة المتجددة وتطوير اقتصاد الهيدروجين ومبادرات احتجاز الكربون.',
    tags: ['energy transition', 'net zero', 'renewables', 'hydrogen'],
    tagsAr: ['التحول في الطاقة', 'صافي الصفر', 'الطاقة المتجددة', 'الهيدروجين'],
    fileSize: '4.1 MB',
    pageCount: 62,
    downloadUrl: '/mock/reports/energy-transition-roadmap-2025.pdf',
    thumbnailUrl: '',
    isFeatured: true,
    language: 'English',
  },
  {
    id: 'rpt-004',
    title: 'Digital Economy & AI Adoption in the Gulf Region',
    titleAr: 'الاقتصاد الرقمي وتبني الذكاء الاصطناعي في منطقة الخليج',
    institution: 'Deloitte',
    institutionAr: 'ديلويت',
    category: 'Technology',
    categoryAr: 'التكنولوجيا',
    publishedDate: '2025-11-30',
    description: 'In-depth study of digital transformation across GCC economies, with a focus on AI adoption rates, fintech growth, e-government maturity, and Abu Dhabi\'s positioning as a regional technology hub.',
    descriptionAr: 'دراسة معمقة للتحول الرقمي في اقتصادات دول مجلس التعاون الخليجي، مع التركيز على معدلات تبني الذكاء الاصطناعي ونمو التكنولوجيا المالية.',
    tags: ['AI', 'digital economy', 'fintech', 'e-government'],
    tagsAr: ['الذكاء الاصطناعي', 'الاقتصاد الرقمي', 'التكنولوجيا المالية', 'الحكومة الإلكترونية'],
    fileSize: '2.4 MB',
    pageCount: 44,
    downloadUrl: '/mock/reports/digital-economy-ai-gulf-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
  {
    id: 'rpt-005',
    title: 'UAE Foreign Trade Statistics & Bilateral Agreements Review',
    titleAr: 'إحصاءات التجارة الخارجية للإمارات ومراجعة الاتفاقيات الثنائية',
    institution: 'World Bank',
    institutionAr: 'البنك الدولي',
    category: 'Trade & Investment',
    categoryAr: 'التجارة والاستثمار',
    publishedDate: '2025-11-15',
    description: 'Detailed analysis of UAE trade flows, top trading partners, sectoral export performance, and the impact of recent Comprehensive Economic Partnership Agreements (CEPAs) on trade diversification.',
    descriptionAr: 'تحليل مفصل لتدفقات التجارة الإماراتية وأهم الشركاء التجاريين وأداء الصادرات القطاعية وتأثير اتفاقيات الشراكة الاقتصادية الشاملة الأخيرة.',
    tags: ['trade', 'exports', 'CEPA', 'bilateral agreements'],
    tagsAr: ['التجارة', 'الصادرات', 'الشراكة الاقتصادية', 'الاتفاقيات الثنائية'],
    fileSize: '1.9 MB',
    pageCount: 32,
    downloadUrl: '/mock/reports/uae-foreign-trade-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'Bilingual',
  },
  {
    id: 'rpt-006',
    title: 'SME Growth Index: Abu Dhabi Business Confidence Survey',
    titleAr: 'مؤشر نمو المنشآت الصغيرة: مسح ثقة الأعمال في أبوظبي',
    institution: 'Abu Dhabi Investment Office',
    institutionAr: 'مكتب أبوظبي للاستثمار',
    category: 'SME & Entrepreneurship',
    categoryAr: 'المنشآت الصغيرة وريادة الأعمال',
    publishedDate: '2025-10-28',
    description: 'Annual survey of 500+ SMEs across Abu Dhabi measuring business confidence, growth expectations, hiring plans, and key challenges. Includes sector-by-sector breakdowns and recommendations for policy support.',
    descriptionAr: 'مسح سنوي لأكثر من 500 منشأة صغيرة ومتوسطة في أبوظبي يقيس ثقة الأعمال وتوقعات النمو وخطط التوظيف والتحديات الرئيسية.',
    tags: ['SME', 'business confidence', 'entrepreneurship', 'Abu Dhabi'],
    tagsAr: ['المنشآت الصغيرة', 'ثقة الأعمال', 'ريادة الأعمال', 'أبوظبي'],
    fileSize: '1.6 MB',
    pageCount: 28,
    downloadUrl: '/mock/reports/sme-growth-index-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'Bilingual',
  },
  {
    id: 'rpt-007',
    title: 'Monetary Policy & Banking Sector Stability Report H2 2025',
    titleAr: 'تقرير السياسة النقدية واستقرار القطاع المصرفي - النصف الثاني 2025',
    institution: 'UAE Central Bank',
    institutionAr: 'المصرف المركزي الإماراتي',
    category: 'Macroeconomics',
    categoryAr: 'الاقتصاد الكلي',
    publishedDate: '2025-12-05',
    description: 'Semi-annual report on monetary policy stance, interest rate environment, banking sector health metrics, credit growth trends, and financial stability indicators across the UAE banking system.',
    descriptionAr: 'تقرير نصف سنوي عن موقف السياسة النقدية وبيئة أسعار الفائدة ومقاييس صحة القطاع المصرفي واتجاهات نمو الائتمان ومؤشرات الاستقرار المالي.',
    tags: ['monetary policy', 'banking', 'interest rates', 'financial stability'],
    tagsAr: ['السياسة النقدية', 'القطاع المصرفي', 'أسعار الفائدة', 'الاستقرار المالي'],
    fileSize: '2.1 MB',
    pageCount: 40,
    downloadUrl: '/mock/reports/monetary-policy-h2-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'Arabic',
  },
  {
    id: 'rpt-008',
    title: 'Abu Dhabi Industrial Strategy: Manufacturing & Supply Chain Analysis',
    titleAr: 'الاستراتيجية الصناعية لأبوظبي: تحليل التصنيع وسلسلة التوريد',
    institution: 'Boston Consulting Group',
    institutionAr: 'مجموعة بوسطن الاستشارية',
    category: 'Trade & Investment',
    categoryAr: 'التجارة والاستثمار',
    publishedDate: '2025-10-10',
    description: 'Strategic review of Abu Dhabi\'s industrial diversification efforts, including manufacturing sector competitiveness, supply chain resilience, and opportunities in advanced manufacturing and Industry 4.0 adoption.',
    descriptionAr: 'مراجعة استراتيجية لجهود التنويع الصناعي في أبوظبي، بما في ذلك تنافسية قطاع التصنيع ومرونة سلسلة التوريد وفرص التصنيع المتقدم.',
    tags: ['manufacturing', 'supply chain', 'Industry 4.0', 'industrial strategy'],
    tagsAr: ['التصنيع', 'سلسلة التوريد', 'الصناعة 4.0', 'الاستراتيجية الصناعية'],
    fileSize: '3.5 MB',
    pageCount: 54,
    downloadUrl: '/mock/reports/ad-industrial-strategy-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
  {
    id: 'rpt-009',
    title: 'Global Credit Outlook: GCC Sovereign & Corporate Ratings',
    titleAr: 'النظرة العالمية للائتمان: تصنيفات السيادية والشركات في الخليج',
    institution: 'S&P Global',
    institutionAr: 'ستاندرد آند بورز العالمية',
    category: 'Macroeconomics',
    categoryAr: 'الاقتصاد الكلي',
    publishedDate: '2025-09-22',
    description: 'Credit rating assessment for GCC sovereign entities and major corporates. Evaluates fiscal buffers, oil price sensitivity, banking sector exposure, and long-term creditworthiness of the UAE economy.',
    descriptionAr: 'تقييم التصنيف الائتماني للكيانات السيادية والشركات الكبرى في دول مجلس التعاون الخليجي. يقيّم الاحتياطيات المالية وحساسية أسعار النفط.',
    tags: ['credit ratings', 'sovereign debt', 'GCC', 'corporate ratings'],
    tagsAr: ['التصنيفات الائتمانية', 'الديون السيادية', 'الخليج', 'تصنيفات الشركات'],
    fileSize: '1.8 MB',
    pageCount: 26,
    downloadUrl: '/mock/reports/gcc-credit-outlook-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
  {
    id: 'rpt-010',
    title: 'Abu Dhabi Venture Capital & Startup Ecosystem Report',
    titleAr: 'تقرير رأس المال الجريء ومنظومة الشركات الناشئة في أبوظبي',
    institution: 'EY',
    institutionAr: 'إرنست ويونغ',
    category: 'SME & Entrepreneurship',
    categoryAr: 'المنشآت الصغيرة وريادة الأعمال',
    publishedDate: '2025-09-05',
    description: 'Comprehensive overview of Abu Dhabi\'s startup ecosystem, including venture capital deal flow, sector-wise funding trends, accelerator programs, and the regulatory environment supporting entrepreneurship.',
    descriptionAr: 'نظرة شاملة على منظومة الشركات الناشئة في أبوظبي، بما في ذلك تدفق صفقات رأس المال الجريء واتجاهات التمويل القطاعية وبرامج التسريع.',
    tags: ['venture capital', 'startups', 'ecosystem', 'funding'],
    tagsAr: ['رأس المال الجريء', 'الشركات الناشئة', 'المنظومة', 'التمويل'],
    fileSize: '2.2 MB',
    pageCount: 38,
    downloadUrl: '/mock/reports/ad-vc-startup-ecosystem-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
  {
    id: 'rpt-011',
    title: 'Sustainable Finance & Green Bonds Market Report - MENA',
    titleAr: 'تقرير التمويل المستدام وسوق السندات الخضراء - الشرق الأوسط وشمال أفريقيا',
    institution: 'KPMG',
    institutionAr: 'كي بي إم جي',
    category: 'Energy',
    categoryAr: 'الطاقة',
    publishedDate: '2025-08-18',
    description: 'Market analysis of green bonds, sustainability-linked loans, and ESG-integrated investment products in the MENA region. Highlights the UAE\'s leadership in sustainable finance issuance and regulatory frameworks.',
    descriptionAr: 'تحليل سوقي للسندات الخضراء والقروض المرتبطة بالاستدامة ومنتجات الاستثمار المتكاملة مع ESG في منطقة الشرق الأوسط وشمال أفريقيا.',
    tags: ['green bonds', 'sustainable finance', 'ESG investing', 'MENA'],
    tagsAr: ['السندات الخضراء', 'التمويل المستدام', 'استثمار ESG', 'الشرق الأوسط'],
    fileSize: '2.7 MB',
    pageCount: 42,
    downloadUrl: '/mock/reports/sustainable-finance-mena-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
  {
    id: 'rpt-012',
    title: 'UAE Technology Sector FDI Attractiveness Index',
    titleAr: 'مؤشر جاذبية الاستثمار الأجنبي المباشر لقطاع التكنولوجيا في الإمارات',
    institution: 'Oxford Economics',
    institutionAr: 'أكسفورد إيكونوميكس',
    category: 'Technology',
    categoryAr: 'التكنولوجيا',
    publishedDate: '2025-08-02',
    description: 'Benchmarking study comparing UAE\'s technology sector FDI attractiveness against global peers. Evaluates talent availability, regulatory incentives, infrastructure quality, and innovation ecosystem maturity.',
    descriptionAr: 'دراسة مقارنة لجاذبية الاستثمار الأجنبي المباشر في قطاع التكنولوجيا بالإمارات مقارنة بالأقران العالميين. يقيّم توفر المواهب والحوافز التنظيمية.',
    tags: ['FDI', 'technology sector', 'innovation', 'benchmarking'],
    tagsAr: ['الاستثمار الأجنبي المباشر', 'قطاع التكنولوجيا', 'الابتكار', 'المقارنة المرجعية'],
    fileSize: '1.5 MB',
    pageCount: 24,
    downloadUrl: '/mock/reports/uae-tech-fdi-index-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'Bilingual',
  },
  {
    id: 'rpt-013',
    title: 'Abu Dhabi Commercial Real Estate: Office & Retail Sector Deep Dive',
    titleAr: 'العقارات التجارية في أبوظبي: تحليل معمق لقطاعي المكاتب والتجزئة',
    institution: 'Moody\'s Analytics',
    institutionAr: 'موديز أناليتكس',
    category: 'Real Estate',
    categoryAr: 'العقارات',
    publishedDate: '2025-07-14',
    description: 'Deep-dive analysis of Abu Dhabi commercial real estate covering office space absorption rates, retail foot traffic trends, rental yield comparisons, and the impact of hybrid work on commercial property demand.',
    descriptionAr: 'تحليل معمق للعقارات التجارية في أبوظبي يغطي معدلات استيعاب المساحات المكتبية واتجاهات حركة التجزئة ومقارنات عوائد الإيجار.',
    tags: ['commercial real estate', 'office market', 'retail', 'rental yields'],
    tagsAr: ['العقارات التجارية', 'سوق المكاتب', 'التجزئة', 'عوائد الإيجار'],
    fileSize: '2.0 MB',
    pageCount: 30,
    downloadUrl: '/mock/reports/ad-commercial-re-deep-dive-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
  {
    id: 'rpt-014',
    title: 'GCC Cross-Border Investment Flows & Capital Markets Review',
    titleAr: 'تدفقات الاستثمار عبر الحدود في الخليج ومراجعة أسواق رأس المال',
    institution: 'Deloitte',
    institutionAr: 'ديلويت',
    category: 'Trade & Investment',
    categoryAr: 'التجارة والاستثمار',
    publishedDate: '2025-07-01',
    description: 'Analysis of cross-border investment patterns within the GCC and with key global markets. Reviews capital market performance, IPO activity, M&A trends, and the growing role of sovereign wealth funds.',
    descriptionAr: 'تحليل أنماط الاستثمار عبر الحدود داخل دول مجلس التعاون الخليجي ومع الأسواق العالمية الرئيسية. يراجع أداء أسواق رأس المال ونشاط الاكتتابات.',
    tags: ['cross-border investment', 'capital markets', 'IPO', 'M&A'],
    tagsAr: ['الاستثمار عبر الحدود', 'أسواق رأس المال', 'الاكتتابات', 'الاندماج والاستحواذ'],
    fileSize: '3.0 MB',
    pageCount: 50,
    downloadUrl: '/mock/reports/gcc-cross-border-investment-2025.pdf',
    thumbnailUrl: '',
    isFeatured: false,
    language: 'English',
  },
]
