export interface Tender {
  id: string
  title: string
  titleAr: string
  issuingOrganization: string
  issuingOrganizationAr: string
  country: string
  countryAr: string
  region: string
  regionAr: string
  sector: string
  sectorAr: string
  tenderType: 'Goods' | 'Services' | 'Works' | 'Consulting'
  publishedDate: string
  deadline: string
  estimatedValue: string
  description: string
  descriptionAr: string
  requirements: string[]
  requirementsAr: string[]
  submissionMethod: string
  submissionMethodAr: string
  referenceNumber: string
  documentUrl: string
  status: 'Open' | 'Closing Soon' | 'Closed'
  isFeatured: boolean
  tags: string[]
  tagsAr: string[]
}

export const organizationColors: Record<string, { bg: string; text: string }> = {
  'World Bank': { bg: 'bg-cyan-700', text: 'text-white' },
  'UN Procurement': { bg: 'bg-blue-600', text: 'text-white' },
  'Saudi Aramco': { bg: 'bg-green-700', text: 'text-white' },
  'ADNOC': { bg: 'bg-teal-600', text: 'text-white' },
  'EU Commission': { bg: 'bg-indigo-600', text: 'text-white' },
  'African Development Bank': { bg: 'bg-emerald-600', text: 'text-white' },
  'Abu Dhabi Government': { bg: 'bg-blue-800', text: 'text-white' },
  'Qatar Energy': { bg: 'bg-rose-700', text: 'text-white' },
  'DEWA': { bg: 'bg-green-600', text: 'text-white' },
  'NEOM': { bg: 'bg-purple-700', text: 'text-white' },
  'Asian Development Bank': { bg: 'bg-sky-700', text: 'text-white' },
  'Kuwait Fund': { bg: 'bg-amber-600', text: 'text-white' },
  'Etihad Rail': { bg: 'bg-gray-700', text: 'text-white' },
  'ACWA Power': { bg: 'bg-orange-600', text: 'text-white' },
  'Ministry of Health - UAE': { bg: 'bg-red-600', text: 'text-white' },
  'Dubai Holding': { bg: 'bg-violet-700', text: 'text-white' },
}

export const sectors = [
  'Infrastructure',
  'Technology',
  'Energy',
  'Healthcare',
  'Logistics',
  'Construction',
  'Consulting',
  'Education',
]

export const sectorsAr: Record<string, string> = {
  'Infrastructure': 'البنية التحتية',
  'Technology': 'التكنولوجيا',
  'Energy': 'الطاقة',
  'Healthcare': 'الرعاية الصحية',
  'Logistics': 'الخدمات اللوجستية',
  'Construction': 'البناء والتشييد',
  'Consulting': 'الاستشارات',
  'Education': 'التعليم',
}

export const regions = [
  'GCC',
  'MENA',
  'Europe',
  'Africa',
  'Asia Pacific',
]

export const regionsAr: Record<string, string> = {
  'GCC': 'دول الخليج',
  'MENA': 'الشرق الأوسط وشمال أفريقيا',
  'Europe': 'أوروبا',
  'Africa': 'أفريقيا',
  'Asia Pacific': 'آسيا والمحيط الهادئ',
}

export const tenderTypes: Tender['tenderType'][] = ['Goods', 'Services', 'Works', 'Consulting']

export const tenderTypesAr: Record<string, string> = {
  'Goods': 'سلع',
  'Services': 'خدمات',
  'Works': 'أعمال',
  'Consulting': 'استشارات',
}

export const countryFlags: Record<string, string> = {
  'Saudi Arabia': '🇸🇦',
  'UAE': '🇦🇪',
  'Qatar': '🇶🇦',
  'Kuwait': '🇰🇼',
  'Germany': '🇩🇪',
  'Belgium': '🇧🇪',
  'Kenya': '🇰🇪',
  'Egypt': '🇪🇬',
  'India': '🇮🇳',
  'Philippines': '🇵🇭',
  'Morocco': '🇲🇦',
  'Oman': '🇴🇲',
}

// Helper: today + N days as ISO string
function futureDate(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() + days)
  return d.toISOString().split('T')[0]
}

function pastDate(days: number): string {
  const d = new Date()
  d.setDate(d.getDate() - days)
  return d.toISOString().split('T')[0]
}

export const tenders: Tender[] = [
  // ── CLOSING SOON (deadline within 7 days) ──────────────────────────────
  {
    id: 'tnd-001',
    title: 'Smart Grid Infrastructure Modernization – Phase II',
    titleAr: 'تحديث البنية التحتية للشبكات الذكية - المرحلة الثانية',
    issuingOrganization: 'DEWA',
    issuingOrganizationAr: 'هيئة كهرباء ومياه دبي',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Energy',
    sectorAr: 'الطاقة',
    tenderType: 'Works',
    publishedDate: pastDate(25),
    deadline: futureDate(3),
    estimatedValue: 'USD 12.5M',
    description: 'Modernization of electrical grid infrastructure across 14 substations in Dubai, including installation of smart meters, automated fault detection systems, and real-time load balancing equipment. Phase II covers the southern and eastern districts.',
    descriptionAr: 'تحديث البنية التحتية للشبكة الكهربائية عبر 14 محطة فرعية في دبي، بما في ذلك تركيب العدادات الذكية وأنظمة كشف الأعطال الآلية ومعدات موازنة الأحمال.',
    requirements: ['Valid UAE trade license', 'ISO 9001:2015 certification', 'Minimum 5 years experience in power grid projects', 'Financial guarantee of AED 2M'],
    requirementsAr: ['رخصة تجارية سارية في الإمارات', 'شهادة ISO 9001:2015', 'خبرة لا تقل عن 5 سنوات في مشاريع الشبكات', 'ضمان مالي بقيمة 2 مليون درهم'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'DEWA-2026-SG-0042',
    documentUrl: '/mock/tenders/dewa-smart-grid-ii.pdf',
    status: 'Closing Soon',
    isFeatured: true,
    tags: ['smart grid', 'energy', 'infrastructure', 'Dubai'],
    tagsAr: ['الشبكات الذكية', 'الطاقة', 'البنية التحتية', 'دبي'],
  },
  {
    id: 'tnd-002',
    title: 'Hospital Medical Equipment Supply – Oncology Department',
    titleAr: 'توريد معدات طبية للمستشفى - قسم الأورام',
    issuingOrganization: 'Ministry of Health - UAE',
    issuingOrganizationAr: 'وزارة الصحة - الإمارات',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Healthcare',
    sectorAr: 'الرعاية الصحية',
    tenderType: 'Goods',
    publishedDate: pastDate(20),
    deadline: futureDate(5),
    estimatedValue: 'USD 4.8M',
    description: 'Procurement of advanced oncology diagnostic and treatment equipment for three government hospitals. Includes linear accelerators, PET-CT scanners, and associated software systems. Delivery, installation, and 3-year maintenance contract included.',
    descriptionAr: 'شراء معدات تشخيص وعلاج الأورام المتقدمة لثلاثة مستشفيات حكومية. يشمل مسرعات خطية وأجهزة تصوير مقطعي بالإصدار البوزيتروني وأنظمة برمجية.',
    requirements: ['FDA or CE Mark certification for all equipment', 'Authorized distributor documentation', 'After-sales service capability in UAE', 'Minimum 3 reference installations in GCC'],
    requirementsAr: ['شهادة FDA أو CE لجميع المعدات', 'وثائق الموزع المعتمد', 'قدرة خدمة ما بعد البيع في الإمارات', '3 مراجع تركيب على الأقل في الخليج'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'MOH-UAE-2026-MED-0118',
    documentUrl: '/mock/tenders/moh-oncology-equipment.pdf',
    status: 'Closing Soon',
    isFeatured: false,
    tags: ['medical equipment', 'healthcare', 'oncology', 'procurement'],
    tagsAr: ['معدات طبية', 'رعاية صحية', 'أورام', 'مشتريات'],
  },
  {
    id: 'tnd-003',
    title: 'Cybersecurity Assessment & SOC Implementation',
    titleAr: 'تقييم الأمن السيبراني وتنفيذ مركز العمليات الأمنية',
    issuingOrganization: 'Abu Dhabi Government',
    issuingOrganizationAr: 'حكومة أبوظبي',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    tenderType: 'Services',
    publishedDate: pastDate(14),
    deadline: futureDate(2),
    estimatedValue: 'USD 3.2M',
    description: 'Comprehensive cybersecurity vulnerability assessment across 12 government entities and establishment of a centralized Security Operations Center (SOC). Includes 24/7 monitoring, incident response framework, and staff training program.',
    descriptionAr: 'تقييم شامل لنقاط الضعف الأمنية عبر 12 جهة حكومية وإنشاء مركز عمليات أمنية مركزي. يشمل المراقبة على مدار الساعة وإطار الاستجابة للحوادث.',
    requirements: ['ISO 27001 certification', 'CISA/CISSP certified team leads', 'Previous SOC deployment in government sector', 'UAE security clearance capability'],
    requirementsAr: ['شهادة ISO 27001', 'قادة فرق حاصلين على CISA/CISSP', 'نشر سابق لمركز عمليات أمنية في القطاع الحكومي', 'القدرة على الحصول على تصريح أمني'],
    submissionMethod: 'Email',
    submissionMethodAr: 'البريد الإلكتروني',
    referenceNumber: 'ADAG-2026-IT-0033',
    documentUrl: '/mock/tenders/adag-cybersecurity-soc.pdf',
    status: 'Closing Soon',
    isFeatured: true,
    tags: ['cybersecurity', 'SOC', 'government', 'IT security'],
    tagsAr: ['الأمن السيبراني', 'مركز عمليات أمنية', 'حكومي', 'أمن تقنية المعلومات'],
  },
  {
    id: 'tnd-004',
    title: 'Cold Chain Logistics Network Expansion – GCC Hub',
    titleAr: 'توسيع شبكة الخدمات اللوجستية للتبريد - مركز الخليج',
    issuingOrganization: 'Qatar Energy',
    issuingOrganizationAr: 'قطر للطاقة',
    country: 'Qatar',
    countryAr: 'قطر',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Logistics',
    sectorAr: 'الخدمات اللوجستية',
    tenderType: 'Services',
    publishedDate: pastDate(18),
    deadline: futureDate(6),
    estimatedValue: 'USD 8.1M',
    description: 'Design and operation of a temperature-controlled logistics network connecting Qatar to key GCC markets. Includes cold storage facilities, refrigerated fleet management, IoT monitoring systems, and last-mile delivery infrastructure.',
    descriptionAr: 'تصميم وتشغيل شبكة لوجستية متحكم في درجة حرارتها تربط قطر بأسواق الخليج الرئيسية. تشمل مرافق التخزين البارد وإدارة أسطول التبريد.',
    requirements: ['ISO 22000 food safety certification', 'Operational fleet of 50+ refrigerated vehicles', 'GDP compliance for pharmaceutical logistics', 'GCC-wide operational license'],
    requirementsAr: ['شهادة ISO 22000 لسلامة الغذاء', 'أسطول تشغيلي من 50+ مركبة مبردة', 'امتثال GDP للخدمات اللوجستية الصيدلانية', 'رخصة تشغيل على مستوى الخليج'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'QE-2026-LOG-0087',
    documentUrl: '/mock/tenders/qe-cold-chain.pdf',
    status: 'Closing Soon',
    isFeatured: false,
    tags: ['cold chain', 'logistics', 'supply chain', 'GCC'],
    tagsAr: ['سلسلة التبريد', 'لوجستية', 'سلسلة التوريد', 'الخليج'],
  },

  // ── OPEN (standard 2–6 weeks) ──────────────────────────────────────────
  {
    id: 'tnd-005',
    title: 'NEOM Residential Community Master Planning – The Line Sector 4',
    titleAr: 'التخطيط الرئيسي للمجتمع السكني في نيوم - قطاع ذا لاين 4',
    issuingOrganization: 'NEOM',
    issuingOrganizationAr: 'نيوم',
    country: 'Saudi Arabia',
    countryAr: 'المملكة العربية السعودية',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Construction',
    sectorAr: 'البناء والتشييد',
    tenderType: 'Consulting',
    publishedDate: pastDate(10),
    deadline: futureDate(28),
    estimatedValue: 'USD 18.5M',
    description: 'Master planning and architectural design consultancy for Sector 4 of The Line residential community. Scope includes urban design, sustainability integration, smart city systems architecture, and community facilities planning for 25,000 residents.',
    descriptionAr: 'استشارات التخطيط الرئيسي والتصميم المعماري للقطاع 4 من مجتمع ذا لاين السكني. يشمل التصميم الحضري وتكامل الاستدامة.',
    requirements: ['Portfolio of 3+ mega-project master plans', 'LEED/Estidama AP on project team', 'Experience in smart city integration', 'Dedicated team of 20+ professionals'],
    requirementsAr: ['ملف أعمال يتضمن 3+ مخططات رئيسية لمشاريع ضخمة', 'معتمد LEED/استدامة في فريق المشروع', 'خبرة في تكامل المدن الذكية', 'فريق مخصص من 20+ محترفاً'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'NEOM-2026-ARC-0156',
    documentUrl: '/mock/tenders/neom-line-sector4.pdf',
    status: 'Open',
    isFeatured: true,
    tags: ['master planning', 'architecture', 'NEOM', 'smart city'],
    tagsAr: ['التخطيط الرئيسي', 'العمارة', 'نيوم', 'المدينة الذكية'],
  },
  {
    id: 'tnd-006',
    title: 'National Railway Signaling System Upgrade',
    titleAr: 'ترقية نظام إشارات السكك الحديدية الوطنية',
    issuingOrganization: 'Etihad Rail',
    issuingOrganizationAr: 'الاتحاد للقطارات',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Infrastructure',
    sectorAr: 'البنية التحتية',
    tenderType: 'Works',
    publishedDate: pastDate(7),
    deadline: futureDate(35),
    estimatedValue: 'USD 45M',
    description: 'Complete upgrade of signaling and train control systems for the 1,200km national railway network. Includes ETCS Level 2 implementation, GSM-R communications, and centralized traffic management system with full redundancy.',
    descriptionAr: 'ترقية كاملة لأنظمة الإشارات والتحكم في القطارات لشبكة السكك الحديدية الوطنية البالغ طولها 1,200 كم. يشمل تنفيذ ETCS المستوى 2.',
    requirements: ['ETCS Level 2 deployment experience', 'IRIS certification', 'Minimum 500km signaling project reference', 'Local JV partner with UAE presence'],
    requirementsAr: ['خبرة نشر ETCS المستوى 2', 'شهادة IRIS', 'مرجع مشروع إشارات بطول 500 كم على الأقل', 'شريك مشروع مشترك محلي في الإمارات'],
    submissionMethod: 'Physical Submission',
    submissionMethodAr: 'تقديم فعلي',
    referenceNumber: 'ER-2026-SIG-0011',
    documentUrl: '/mock/tenders/etihad-rail-signaling.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['railway', 'signaling', 'infrastructure', 'transport'],
    tagsAr: ['سكك حديدية', 'إشارات', 'بنية تحتية', 'نقل'],
  },
  {
    id: 'tnd-007',
    title: 'Renewable Energy Training Academy Establishment',
    titleAr: 'إنشاء أكاديمية تدريب الطاقة المتجددة',
    issuingOrganization: 'ACWA Power',
    issuingOrganizationAr: 'أكوا باور',
    country: 'Saudi Arabia',
    countryAr: 'المملكة العربية السعودية',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Education',
    sectorAr: 'التعليم',
    tenderType: 'Services',
    publishedDate: pastDate(5),
    deadline: futureDate(30),
    estimatedValue: 'USD 6.2M',
    description: 'Design and delivery of a comprehensive renewable energy training academy. Includes curriculum development for solar PV, wind, and green hydrogen technologies, simulation labs setup, instructor certification program, and first-year operations.',
    descriptionAr: 'تصميم وتقديم أكاديمية تدريب شاملة في مجال الطاقة المتجددة. يشمل تطوير المناهج للطاقة الشمسية وطاقة الرياح وتقنيات الهيدروجين الأخضر.',
    requirements: ['Accredited training provider status', 'Renewable energy sector expertise', 'E-learning platform capability', 'GCC regional delivery experience'],
    requirementsAr: ['وضع مزود تدريب معتمد', 'خبرة في قطاع الطاقة المتجددة', 'القدرة على منصة التعلم الإلكتروني', 'خبرة التقديم الإقليمي في الخليج'],
    submissionMethod: 'Email',
    submissionMethodAr: 'البريد الإلكتروني',
    referenceNumber: 'ACWA-2026-EDU-0023',
    documentUrl: '/mock/tenders/acwa-training-academy.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['training', 'renewable energy', 'education', 'academy'],
    tagsAr: ['تدريب', 'طاقة متجددة', 'تعليم', 'أكاديمية'],
  },
  {
    id: 'tnd-008',
    title: 'Pan-African Digital Identity Platform Development',
    titleAr: 'تطوير منصة الهوية الرقمية لعموم أفريقيا',
    issuingOrganization: 'African Development Bank',
    issuingOrganizationAr: 'البنك الأفريقي للتنمية',
    country: 'Kenya',
    countryAr: 'كينيا',
    region: 'Africa',
    regionAr: 'أفريقيا',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    tenderType: 'Services',
    publishedDate: pastDate(8),
    deadline: futureDate(42),
    estimatedValue: 'USD 15M',
    description: 'Development and deployment of a blockchain-based digital identity platform serving 5 pilot African nations. Includes biometric enrollment systems, mobile-first verification apps, interoperability framework, and data privacy compliance across jurisdictions.',
    descriptionAr: 'تطوير ونشر منصة هوية رقمية قائمة على البلوكشين تخدم 5 دول أفريقية رائدة. تشمل أنظمة التسجيل البيومتري وتطبيقات التحقق.',
    requirements: ['Digital identity platform deployment references', 'Biometric systems integration capability', 'Data protection framework experience (GDPR equivalent)', 'Multi-country project management capability'],
    requirementsAr: ['مراجع نشر منصة هوية رقمية', 'القدرة على تكامل الأنظمة البيومترية', 'خبرة في إطار حماية البيانات', 'القدرة على إدارة المشاريع متعددة الدول'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'AFDB-2026-DIG-0045',
    documentUrl: '/mock/tenders/afdb-digital-identity.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['digital identity', 'blockchain', 'Africa', 'biometrics'],
    tagsAr: ['الهوية الرقمية', 'بلوكشين', 'أفريقيا', 'القياسات الحيوية'],
  },
  {
    id: 'tnd-009',
    title: 'EU Green Hydrogen Infrastructure Feasibility Study',
    titleAr: 'دراسة جدوى البنية التحتية للهيدروجين الأخضر في الاتحاد الأوروبي',
    issuingOrganization: 'EU Commission',
    issuingOrganizationAr: 'المفوضية الأوروبية',
    country: 'Belgium',
    countryAr: 'بلجيكا',
    region: 'Europe',
    regionAr: 'أوروبا',
    sector: 'Energy',
    sectorAr: 'الطاقة',
    tenderType: 'Consulting',
    publishedDate: pastDate(12),
    deadline: futureDate(21),
    estimatedValue: 'EUR 8.5M',
    description: 'Comprehensive feasibility study for green hydrogen production, transport, and storage infrastructure across the EU-MENA corridor. Covers electrolyzer technology assessment, pipeline network modeling, and cross-border regulatory harmonization analysis.',
    descriptionAr: 'دراسة جدوى شاملة للبنية التحتية لإنتاج ونقل وتخزين الهيدروجين الأخضر عبر ممر الاتحاد الأوروبي والشرق الأوسط وشمال أفريقيا.',
    requirements: ['Hydrogen infrastructure project references', 'EU energy regulation expertise', 'Cross-border energy corridor experience', 'Technical team with PhD-level researchers'],
    requirementsAr: ['مراجع مشاريع البنية التحتية للهيدروجين', 'خبرة في تنظيم الطاقة الأوروبي', 'خبرة ممرات الطاقة العابرة للحدود', 'فريق تقني بباحثين حاملي درجة الدكتوراه'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'EC-2026-H2-0012',
    documentUrl: '/mock/tenders/eu-green-hydrogen.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['green hydrogen', 'feasibility study', 'EU', 'energy transition'],
    tagsAr: ['الهيدروجين الأخضر', 'دراسة جدوى', 'الاتحاد الأوروبي', 'التحول في الطاقة'],
  },
  {
    id: 'tnd-010',
    title: 'ADNOC Offshore Platform Maintenance – Das Island Complex',
    titleAr: 'صيانة المنصات البحرية لأدنوك - مجمع جزيرة داس',
    issuingOrganization: 'ADNOC',
    issuingOrganizationAr: 'أدنوك',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Energy',
    sectorAr: 'الطاقة',
    tenderType: 'Works',
    publishedDate: pastDate(6),
    deadline: futureDate(25),
    estimatedValue: 'Undisclosed',
    description: 'Planned maintenance and integrity management services for the Das Island offshore complex comprising 8 platforms. Includes structural inspection, corrosion management, safety system upgrades, and environmental compliance monitoring.',
    descriptionAr: 'خدمات الصيانة المخططة وإدارة السلامة لمجمع جزيرة داس البحري المكون من 8 منصات. يشمل الفحص الهيكلي وإدارة التآكل.',
    requirements: ['Offshore maintenance track record (min 10 years)', 'ADNOC ICV certification', 'HSE management system (OHSAS 18001)', 'Offshore crew mobilization capability'],
    requirementsAr: ['سجل صيانة بحرية (10 سنوات على الأقل)', 'شهادة القيمة المحلية المضافة من أدنوك', 'نظام إدارة الصحة والسلامة', 'القدرة على تعبئة الطاقم البحري'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'ADNOC-2026-OFF-0234',
    documentUrl: '/mock/tenders/adnoc-das-island.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['offshore', 'oil & gas', 'maintenance', 'ADNOC'],
    tagsAr: ['بحري', 'نفط وغاز', 'صيانة', 'أدنوك'],
  },
  {
    id: 'tnd-011',
    title: 'Rural Water Supply & Sanitation Program – Phase III',
    titleAr: 'برنامج إمدادات المياه والصرف الصحي الريفي - المرحلة الثالثة',
    issuingOrganization: 'World Bank',
    issuingOrganizationAr: 'البنك الدولي',
    country: 'Egypt',
    countryAr: 'مصر',
    region: 'MENA',
    regionAr: 'الشرق الأوسط وشمال أفريقيا',
    sector: 'Infrastructure',
    sectorAr: 'البنية التحتية',
    tenderType: 'Works',
    publishedDate: pastDate(4),
    deadline: futureDate(38),
    estimatedValue: 'USD 32M',
    description: 'Design-build of water supply and wastewater treatment systems serving 150 rural communities in Upper Egypt. Includes water treatment plants, distribution networks, sewage systems, and community awareness programs.',
    descriptionAr: 'تصميم وبناء أنظمة إمداد المياه ومعالجة مياه الصرف لخدمة 150 مجتمعاً ريفياً في صعيد مصر. يشمل محطات معالجة المياه وشبكات التوزيع.',
    requirements: ['World Bank procurement guidelines experience', 'Water/wastewater project portfolio >USD 50M', 'Rural project delivery track record', 'Local partnership required'],
    requirementsAr: ['خبرة في إرشادات مشتريات البنك الدولي', 'محفظة مشاريع المياه والصرف >50 مليون دولار', 'سجل تنفيذ مشاريع ريفية', 'مطلوب شراكة محلية'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'WB-2026-WASH-0078',
    documentUrl: '/mock/tenders/wb-egypt-water.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['water supply', 'sanitation', 'World Bank', 'Egypt'],
    tagsAr: ['إمدادات المياه', 'صرف صحي', 'البنك الدولي', 'مصر'],
  },
  {
    id: 'tnd-012',
    title: 'UN Peacekeeping Mission IT Infrastructure Supply',
    titleAr: 'توريد البنية التحتية لتكنولوجيا المعلومات لبعثة حفظ السلام',
    issuingOrganization: 'UN Procurement',
    issuingOrganizationAr: 'مشتريات الأمم المتحدة',
    country: 'Philippines',
    countryAr: 'الفلبين',
    region: 'Asia Pacific',
    regionAr: 'آسيا والمحيط الهادئ',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    tenderType: 'Goods',
    publishedDate: pastDate(3),
    deadline: futureDate(20),
    estimatedValue: 'USD 2.1M',
    description: 'Supply of IT equipment and communications infrastructure for UN peacekeeping operations including ruggedized laptops, satellite communication terminals, portable server units, and solar-powered charging stations for field deployment.',
    descriptionAr: 'توريد معدات تكنولوجيا المعلومات والبنية التحتية للاتصالات لعمليات حفظ السلام التابعة للأمم المتحدة. يشمل أجهزة كمبيوتر محمولة معززة ومحطات اتصالات.',
    requirements: ['UN Global Marketplace registration', 'MIL-STD compliant product range', 'Global logistics and delivery capability', 'Previous UN supply contract preferred'],
    requirementsAr: ['تسجيل في السوق العالمي للأمم المتحدة', 'منتجات متوافقة مع معايير MIL-STD', 'القدرة اللوجستية والتوصيل العالمي', 'يفضل عقد توريد سابق مع الأمم المتحدة'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'UN-2026-ICT-0456',
    documentUrl: '/mock/tenders/un-it-infrastructure.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['IT equipment', 'UN', 'communications', 'peacekeeping'],
    tagsAr: ['معدات تقنية', 'الأمم المتحدة', 'اتصالات', 'حفظ السلام'],
  },
  {
    id: 'tnd-013',
    title: 'Economic Diversification Strategy Advisory – Kuwait 2035',
    titleAr: 'استشارات استراتيجية التنويع الاقتصادي - رؤية الكويت 2035',
    issuingOrganization: 'Kuwait Fund',
    issuingOrganizationAr: 'الصندوق الكويتي',
    country: 'Kuwait',
    countryAr: 'الكويت',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Consulting',
    sectorAr: 'الاستشارات',
    tenderType: 'Consulting',
    publishedDate: pastDate(9),
    deadline: futureDate(18),
    estimatedValue: 'USD 5.5M',
    description: 'Strategic advisory engagement to develop Kuwait\'s economic diversification roadmap aligned with Vision 2035. Covers non-oil sector development, private sector growth strategy, FDI attraction framework, and SME ecosystem development.',
    descriptionAr: 'مشاركة استشارية استراتيجية لتطوير خريطة طريق التنويع الاقتصادي للكويت المتوافقة مع رؤية 2035.',
    requirements: ['Top-tier consulting firm or equivalent', 'GCC economic advisory references', 'National vision/strategy development experience', 'Arabic language capability required'],
    requirementsAr: ['شركة استشارات من المستوى الأول أو ما يعادلها', 'مراجع استشارات اقتصادية خليجية', 'خبرة تطوير رؤية/استراتيجية وطنية', 'مطلوب القدرة باللغة العربية'],
    submissionMethod: 'Physical Submission',
    submissionMethodAr: 'تقديم فعلي',
    referenceNumber: 'KF-2026-ADV-0019',
    documentUrl: '/mock/tenders/kuwait-diversification.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['economic diversification', 'strategy', 'Kuwait', 'advisory'],
    tagsAr: ['التنويع الاقتصادي', 'استراتيجية', 'الكويت', 'استشارات'],
  },
  {
    id: 'tnd-014',
    title: 'Sustainable Affordable Housing Construction – 2,000 Units',
    titleAr: 'بناء مساكن ميسورة ومستدامة - 2,000 وحدة',
    issuingOrganization: 'Asian Development Bank',
    issuingOrganizationAr: 'بنك التنمية الآسيوي',
    country: 'India',
    countryAr: 'الهند',
    region: 'Asia Pacific',
    regionAr: 'آسيا والمحيط الهادئ',
    sector: 'Construction',
    sectorAr: 'البناء والتشييد',
    tenderType: 'Works',
    publishedDate: pastDate(11),
    deadline: futureDate(32),
    estimatedValue: 'USD 28M',
    description: 'Design and construction of 2,000 affordable housing units in Rajasthan, India using sustainable construction methods. Includes solar rooftop systems, rainwater harvesting, community facilities, and green building certification to GRIHA standards.',
    descriptionAr: 'تصميم وبناء 2,000 وحدة سكنية ميسورة في راجستان بالهند باستخدام أساليب البناء المستدام. يشمل أنظمة الطاقة الشمسية وحصاد مياه الأمطار.',
    requirements: ['ADB procurement experience', 'Green building certification capability', 'Housing project portfolio >1,000 units', 'Sustainable construction expertise'],
    requirementsAr: ['خبرة مشتريات بنك التنمية الآسيوي', 'القدرة على شهادات المباني الخضراء', 'محفظة مشاريع إسكان >1,000 وحدة', 'خبرة البناء المستدام'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'ADB-2026-HSG-0034',
    documentUrl: '/mock/tenders/adb-india-housing.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['affordable housing', 'sustainable', 'India', 'construction'],
    tagsAr: ['إسكان ميسور', 'مستدام', 'الهند', 'بناء'],
  },
  {
    id: 'tnd-015',
    title: 'Smart Port Automation System – Khalifa Port Expansion',
    titleAr: 'نظام أتمتة الميناء الذكي - توسعة ميناء خليفة',
    issuingOrganization: 'Abu Dhabi Government',
    issuingOrganizationAr: 'حكومة أبوظبي',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Logistics',
    sectorAr: 'الخدمات اللوجستية',
    tenderType: 'Goods',
    publishedDate: pastDate(2),
    deadline: futureDate(40),
    estimatedValue: 'USD 22M',
    description: 'Supply and integration of automated container handling systems for Khalifa Port expansion project. Includes automated stacking cranes, AGVs, terminal operating system software, and 5G connectivity infrastructure for real-time operations.',
    descriptionAr: 'توريد وتكامل أنظمة مناولة الحاويات الآلية لمشروع توسعة ميناء خليفة. يشمل الرافعات الآلية ومركبات النقل الآلية.',
    requirements: ['Port automation system references', 'TOS software integration capability', 'UAE-based service support team', 'Project completion within 24 months'],
    requirementsAr: ['مراجع أنظمة أتمتة الموانئ', 'القدرة على تكامل برمجيات نظام تشغيل المحطة', 'فريق دعم خدمات في الإمارات', 'إنجاز المشروع خلال 24 شهراً'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'ADAG-2026-PRT-0067',
    documentUrl: '/mock/tenders/adag-khalifa-port.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['port automation', 'logistics', 'smart port', 'Abu Dhabi'],
    tagsAr: ['أتمتة الموانئ', 'لوجستية', 'ميناء ذكي', 'أبوظبي'],
  },
  {
    id: 'tnd-016',
    title: 'Vocational Training Centers Equipment Supply – Morocco',
    titleAr: 'توريد معدات مراكز التدريب المهني - المغرب',
    issuingOrganization: 'African Development Bank',
    issuingOrganizationAr: 'البنك الأفريقي للتنمية',
    country: 'Morocco',
    countryAr: 'المغرب',
    region: 'Africa',
    regionAr: 'أفريقيا',
    sector: 'Education',
    sectorAr: 'التعليم',
    tenderType: 'Goods',
    publishedDate: pastDate(6),
    deadline: futureDate(22),
    estimatedValue: 'EUR 3.8M',
    description: 'Supply and installation of workshop equipment and digital learning tools for 15 vocational training centers across Morocco. Covers automotive, electrical, IT, and hospitality training equipment with 2-year warranty and maintenance.',
    descriptionAr: 'توريد وتركيب معدات الورش وأدوات التعلم الرقمي لـ 15 مركز تدريب مهني في المغرب.',
    requirements: ['Equipment supply references in education sector', 'After-sales network in North Africa', 'Multi-site delivery logistics capability', 'Training and handover program'],
    requirementsAr: ['مراجع توريد معدات في قطاع التعليم', 'شبكة خدمة ما بعد البيع في شمال أفريقيا', 'القدرة اللوجستية للتوصيل لمواقع متعددة', 'برنامج تدريب وتسليم'],
    submissionMethod: 'Email',
    submissionMethodAr: 'البريد الإلكتروني',
    referenceNumber: 'AFDB-2026-EDU-0089',
    documentUrl: '/mock/tenders/afdb-morocco-vocational.pdf',
    status: 'Open',
    isFeatured: false,
    tags: ['vocational training', 'education', 'Morocco', 'equipment'],
    tagsAr: ['تدريب مهني', 'تعليم', 'المغرب', 'معدات'],
  },

  // ── CLOSED ─────────────────────────────────────────────────────────────
  {
    id: 'tnd-017',
    title: 'Dubai Expo Legacy District – Landscape Architecture',
    titleAr: 'منطقة إرث إكسبو دبي - هندسة المناظر الطبيعية',
    issuingOrganization: 'Dubai Holding',
    issuingOrganizationAr: 'دبي القابضة',
    country: 'UAE',
    countryAr: 'الإمارات',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Construction',
    sectorAr: 'البناء والتشييد',
    tenderType: 'Consulting',
    publishedDate: pastDate(60),
    deadline: pastDate(5),
    estimatedValue: 'USD 7.8M',
    description: 'Landscape architecture and urban design consultancy for the Expo 2020 legacy district transformation. Included public realm design, sustainable irrigation systems, heat mitigation strategies, and biodiversity integration plan.',
    descriptionAr: 'استشارات هندسة المناظر الطبيعية والتصميم الحضري لتحويل منطقة إرث إكسبو 2020.',
    requirements: ['Landscape architecture portfolio in arid climates', 'ASLA or equivalent accreditation', 'Sustainable landscape expertise', 'UAE project experience preferred'],
    requirementsAr: ['محفظة هندسة مناظر طبيعية في المناخات الجافة', 'اعتماد ASLA أو ما يعادله', 'خبرة المناظر الطبيعية المستدامة', 'يفضل خبرة مشاريع في الإمارات'],
    submissionMethod: 'Online Portal',
    submissionMethodAr: 'بوابة إلكترونية',
    referenceNumber: 'DH-2026-LAND-0044',
    documentUrl: '/mock/tenders/dh-expo-landscape.pdf',
    status: 'Closed',
    isFeatured: false,
    tags: ['landscape', 'urban design', 'Expo', 'Dubai'],
    tagsAr: ['مناظر طبيعية', 'تصميم حضري', 'إكسبو', 'دبي'],
  },
  {
    id: 'tnd-018',
    title: 'Oman National ERP System for Public Sector',
    titleAr: 'نظام تخطيط الموارد الوطني لعمان للقطاع العام',
    issuingOrganization: 'World Bank',
    issuingOrganizationAr: 'البنك الدولي',
    country: 'Oman',
    countryAr: 'عمان',
    region: 'GCC',
    regionAr: 'دول الخليج',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    tenderType: 'Services',
    publishedDate: pastDate(90),
    deadline: pastDate(15),
    estimatedValue: 'USD 20M',
    description: 'Implementation of a unified ERP system across 8 Omani government ministries covering finance, HR, procurement, and asset management. Included data migration, change management, and 5-year managed services.',
    descriptionAr: 'تنفيذ نظام تخطيط موارد موحد عبر 8 وزارات حكومية عمانية يغطي المالية والموارد البشرية والمشتريات وإدارة الأصول.',
    requirements: ['Government ERP implementation references', 'SAP/Oracle certified partnership', 'Arabic language system localization', 'GCC data residency compliance'],
    requirementsAr: ['مراجع تنفيذ ERP حكومي', 'شراكة معتمدة من SAP/Oracle', 'توطين النظام باللغة العربية', 'امتثال إقامة البيانات في الخليج'],
    submissionMethod: 'Physical Submission',
    submissionMethodAr: 'تقديم فعلي',
    referenceNumber: 'WB-2025-ERP-0112',
    documentUrl: '/mock/tenders/wb-oman-erp.pdf',
    status: 'Closed',
    isFeatured: false,
    tags: ['ERP', 'government', 'digital transformation', 'Oman'],
    tagsAr: ['تخطيط الموارد', 'حكومي', 'التحول الرقمي', 'عمان'],
  },
]
