// ─── Knowledge Sharing & Upskilling Programs — Seed Data ─────────────────────
// Used by: app/services/knowledge-sharing/page.tsx (member browse experience)

export interface ProgramSession {
  date: string
  spotsAvailable: number
  location: string
  locationAr: string
}

export interface Program {
  id: string
  programType: 'Knowledge Series' | 'Upskilling Program'
  programTypeAr: 'سلسلة المعرفة' | 'برنامج التطوير المهني'
  title: string
  titleAr: string
  provider: string
  providerAr: string
  sector: string
  sectorAr: string
  description: string
  descriptionAr: string
  duration: string
  durationAr: string
  format: 'In-Person' | 'Online' | 'Hybrid'
  formatAr: 'حضوري' | 'عبر الإنترنت' | 'مدمج'
  language: 'English' | 'Arabic' | 'Bilingual'
  level: 'Beginner' | 'Intermediate' | 'Advanced'
  levelAr: 'مبتدئ' | 'متوسط' | 'متقدم'
  upcomingSessions: ProgramSession[]
  tags: string[]
  tagsAr: string[]
  isFeatured: boolean
  certificationOffered: boolean
  targetAudience: string
  targetAudienceAr: string
}

export const PROGRAMS: Program[] = [
  {
    id: 'ks-001',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'AI & Digital Transformation for Business Leaders',
    titleAr: 'الذكاء الاصطناعي والتحول الرقمي لقادة الأعمال',
    provider: 'ADCCI in partnership with PwC',
    providerAr: 'غرفة أبوظبي بالتعاون مع برايس ووترهاوس كوبرز',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    description: 'An executive knowledge series on leveraging AI, automation, and digital tools to drive business growth. Covers practical use cases, ROI frameworks, and implementation roadmaps tailored to UAE market dynamics.',
    descriptionAr: 'سلسلة معرفية تنفيذية حول الاستفادة من الذكاء الاصطناعي والأتمتة والأدوات الرقمية لدفع نمو الأعمال. تغطي حالات الاستخدام العملية وأطر العائد على الاستثمار وخرائط التنفيذ المصممة لديناميكيات السوق الإماراتي.',
    duration: '2 days',
    durationAr: 'يومان',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'English',
    level: 'Advanced',
    levelAr: 'متقدم',
    upcomingSessions: [
      { date: '2026-03-15', spotsAvailable: 8, location: 'ADCCI HQ — Executive Suite', locationAr: 'مقر الغرفة — الجناح التنفيذي' },
      { date: '2026-04-20', spotsAvailable: 15, location: 'ADCCI HQ — Executive Suite', locationAr: 'مقر الغرفة — الجناح التنفيذي' },
    ],
    tags: ['AI', 'Digital Transformation', 'Automation', 'Strategy'],
    tagsAr: ['الذكاء الاصطناعي', 'التحول الرقمي', 'الأتمتة', 'الاستراتيجية'],
    isFeatured: true,
    certificationOffered: true,
    targetAudience: 'C-Suite executives, Directors, Senior Managers',
    targetAudienceAr: 'المديرون التنفيذيون ونواب الرؤساء وكبار المديرين',
  },
  {
    id: 'ks-002',
    programType: 'Upskilling Program',
    programTypeAr: 'برنامج التطوير المهني',
    title: 'ESG Reporting & Compliance Workshop',
    titleAr: 'ورشة إعداد تقارير الاستدامة والامتثال',
    provider: 'ADCCI in partnership with Deloitte',
    providerAr: 'غرفة أبوظبي بالتعاون مع ديلويت',
    sector: 'Sustainability',
    sectorAr: 'الاستدامة',
    description: 'Hands-on program covering GRI, SASB, and UAE-specific ESG disclosure requirements. Participants will learn to build comprehensive sustainability reports aligned with Abu Dhabi regulatory frameworks.',
    descriptionAr: 'برنامج عملي يغطي متطلبات إعداد التقارير وفق معايير GRI وSASB ومتطلبات الإفصاح البيئي والاجتماعي والحوكمة الخاصة بالإمارات.',
    duration: '3 days',
    durationAr: '3 أيام',
    format: 'Hybrid',
    formatAr: 'مدمج',
    language: 'Bilingual',
    level: 'Intermediate',
    levelAr: 'متوسط',
    upcomingSessions: [
      { date: '2026-03-22', spotsAvailable: 12, location: 'ADCCI Training Center', locationAr: 'مركز تدريب الغرفة' },
      { date: '2026-05-10', spotsAvailable: 20, location: 'Virtual (Zoom)', locationAr: 'افتراضي (زووم)' },
      { date: '2026-06-15', spotsAvailable: 18, location: 'ADCCI Training Center', locationAr: 'مركز تدريب الغرفة' },
    ],
    tags: ['ESG', 'Sustainability', 'Compliance', 'Reporting'],
    tagsAr: ['الاستدامة', 'الامتثال', 'التقارير', 'الحوكمة البيئية'],
    isFeatured: true,
    certificationOffered: true,
    targetAudience: 'Sustainability officers, Compliance managers, CSR teams',
    targetAudienceAr: 'مسؤولو الاستدامة ومديرو الامتثال وفرق المسؤولية الاجتماعية',
  },
  {
    id: 'ks-003',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'Financial Planning & Risk Management',
    titleAr: 'التخطيط المالي وإدارة المخاطر',
    provider: 'ADCCI in partnership with EY',
    providerAr: 'غرفة أبوظبي بالتعاون مع إرنست ويونغ',
    sector: 'Finance',
    sectorAr: 'المالية',
    description: 'A comprehensive series on financial planning, treasury management, and enterprise risk frameworks. Includes case studies from leading UAE organizations and interactive modeling exercises.',
    descriptionAr: 'سلسلة شاملة حول التخطيط المالي وإدارة الخزينة وأطر المخاطر المؤسسية. تتضمن دراسات حالة من مؤسسات إماراتية رائدة وتمارين نمذجة تفاعلية.',
    duration: '4 hours',
    durationAr: '4 ساعات',
    format: 'Online',
    formatAr: 'عبر الإنترنت',
    language: 'English',
    level: 'Intermediate',
    levelAr: 'متوسط',
    upcomingSessions: [
      { date: '2026-03-10', spotsAvailable: 30, location: 'Virtual (Teams)', locationAr: 'افتراضي (تيمز)' },
      { date: '2026-04-14', spotsAvailable: 30, location: 'Virtual (Teams)', locationAr: 'افتراضي (تيمز)' },
    ],
    tags: ['Finance', 'Risk Management', 'Treasury', 'Planning'],
    tagsAr: ['المالية', 'إدارة المخاطر', 'الخزينة', 'التخطيط'],
    isFeatured: false,
    certificationOffered: false,
    targetAudience: 'CFOs, Finance managers, Risk officers',
    targetAudienceAr: 'المديرون الماليون ومديرو المخاطر',
  },
  {
    id: 'ks-004',
    programType: 'Upskilling Program',
    programTypeAr: 'برنامج التطوير المهني',
    title: 'Leadership Excellence Program',
    titleAr: 'برنامج التميز القيادي',
    provider: 'ADCCI in partnership with INSEAD',
    providerAr: 'غرفة أبوظبي بالتعاون مع إنسياد',
    sector: 'Leadership',
    sectorAr: 'القيادة',
    description: 'An intensive leadership development program covering strategic thinking, change management, and organizational transformation. Features peer-to-peer learning and executive coaching sessions.',
    descriptionAr: 'برنامج مكثف لتطوير القيادة يغطي التفكير الاستراتيجي وإدارة التغيير والتحول المؤسسي. يتضمن التعلم بين الأقران وجلسات التدريب التنفيذي.',
    duration: '6 weeks online',
    durationAr: '6 أسابيع عبر الإنترنت',
    format: 'Online',
    formatAr: 'عبر الإنترنت',
    language: 'English',
    level: 'Advanced',
    levelAr: 'متقدم',
    upcomingSessions: [
      { date: '2026-04-01', spotsAvailable: 3, location: 'Virtual (INSEAD Platform)', locationAr: 'افتراضي (منصة إنسياد)' },
      { date: '2026-07-01', spotsAvailable: 20, location: 'Virtual (INSEAD Platform)', locationAr: 'افتراضي (منصة إنسياد)' },
    ],
    tags: ['Leadership', 'Management', 'Strategy', 'Executive'],
    tagsAr: ['القيادة', 'الإدارة', 'الاستراتيجية', 'تنفيذي'],
    isFeatured: true,
    certificationOffered: true,
    targetAudience: 'Senior leaders, General managers, Aspiring executives',
    targetAudienceAr: 'كبار القادة والمديرون العامون والتنفيذيون الطموحون',
  },
  {
    id: 'ks-005',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'UAE Labor Law Updates & HR Best Practices',
    titleAr: 'تحديثات قانون العمل الإماراتي وأفضل ممارسات الموارد البشرية',
    provider: 'ADCCI in partnership with Baker McKenzie',
    providerAr: 'غرفة أبوظبي بالتعاون مع بيكر ماكنزي',
    sector: 'HR & People',
    sectorAr: 'الموارد البشرية',
    description: 'Stay updated on the latest UAE labor regulations including Emiratization targets, end-of-service benefits changes, and remote work policies. Interactive Q&A with legal experts.',
    descriptionAr: 'ابقَ مطلعاً على أحدث لوائح العمل الإماراتية بما في ذلك أهداف التوطين وتغييرات مكافأة نهاية الخدمة وسياسات العمل عن بُعد.',
    duration: '3 hours',
    durationAr: '3 ساعات',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'Bilingual',
    level: 'Beginner',
    levelAr: 'مبتدئ',
    upcomingSessions: [
      { date: '2026-03-18', spotsAvailable: 25, location: 'ADCCI Auditorium', locationAr: 'قاعة الغرفة' },
      { date: '2026-05-20', spotsAvailable: 25, location: 'ADCCI Auditorium', locationAr: 'قاعة الغرفة' },
    ],
    tags: ['Labor Law', 'HR', 'Emiratization', 'Compliance'],
    tagsAr: ['قانون العمل', 'الموارد البشرية', 'التوطين', 'الامتثال'],
    isFeatured: false,
    certificationOffered: false,
    targetAudience: 'HR managers, Business owners, Legal advisors',
    targetAudienceAr: 'مديرو الموارد البشرية وأصحاب الأعمال والمستشارون القانونيون',
  },
  {
    id: 'ks-006',
    programType: 'Upskilling Program',
    programTypeAr: 'برنامج التطوير المهني',
    title: 'Digital Marketing & E-Commerce Bootcamp',
    titleAr: 'معسكر التسويق الرقمي والتجارة الإلكترونية',
    provider: 'ADCCI in partnership with Google',
    providerAr: 'غرفة أبوظبي بالتعاون مع جوجل',
    sector: 'Marketing',
    sectorAr: 'التسويق',
    description: 'A practical bootcamp covering SEO, social media advertising, Google Ads, and e-commerce platform setup. Designed for SMEs looking to grow their digital presence in the UAE and GCC markets.',
    descriptionAr: 'معسكر عملي يغطي تحسين محركات البحث والإعلانات على وسائل التواصل الاجتماعي وإعلانات جوجل وإنشاء منصات التجارة الإلكترونية.',
    duration: '5 days',
    durationAr: '5 أيام',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'English',
    level: 'Beginner',
    levelAr: 'مبتدئ',
    upcomingSessions: [
      { date: '2026-03-24', spotsAvailable: 4, location: 'ADCCI Innovation Hub', locationAr: 'مركز الابتكار — الغرفة' },
      { date: '2026-05-05', spotsAvailable: 15, location: 'ADCCI Innovation Hub', locationAr: 'مركز الابتكار — الغرفة' },
    ],
    tags: ['Marketing', 'E-Commerce', 'SEO', 'Social Media'],
    tagsAr: ['التسويق', 'التجارة الإلكترونية', 'تحسين محركات البحث', 'وسائل التواصل'],
    isFeatured: false,
    certificationOffered: true,
    targetAudience: 'SME owners, Marketing teams, Entrepreneurs',
    targetAudienceAr: 'أصحاب المشاريع الصغيرة وفرق التسويق ورواد الأعمال',
  },
  {
    id: 'ks-007',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'Supply Chain Resilience & Logistics Optimization',
    titleAr: 'مرونة سلسلة التوريد وتحسين الخدمات اللوجستية',
    provider: 'ADCCI in partnership with McKinsey',
    providerAr: 'غرفة أبوظبي بالتعاون مع ماكنزي',
    sector: 'Operations',
    sectorAr: 'العمليات',
    description: 'Expert insights on building resilient supply chains, leveraging Abu Dhabi\'s logistics infrastructure, and implementing lean operations. Includes site visits to KIZAD and Khalifa Port.',
    descriptionAr: 'رؤى متخصصة حول بناء سلاسل توريد مرنة والاستفادة من البنية التحتية اللوجستية لأبوظبي وتنفيذ العمليات الرشيقة.',
    duration: '1 day',
    durationAr: 'يوم واحد',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'English',
    level: 'Intermediate',
    levelAr: 'متوسط',
    upcomingSessions: [
      { date: '2026-04-08', spotsAvailable: 20, location: 'KIZAD Business Center', locationAr: 'مركز أعمال كيزاد' },
      { date: '2026-06-10', spotsAvailable: 20, location: 'Khalifa Port Venue', locationAr: 'مقر ميناء خليفة' },
    ],
    tags: ['Supply Chain', 'Logistics', 'Operations', 'Lean'],
    tagsAr: ['سلسلة التوريد', 'اللوجستيات', 'العمليات', 'الإدارة الرشيقة'],
    isFeatured: false,
    certificationOffered: false,
    targetAudience: 'Operations managers, Supply chain leaders, Procurement heads',
    targetAudienceAr: 'مديرو العمليات وقادة سلسلة التوريد ورؤساء المشتريات',
  },
  {
    id: 'ks-008',
    programType: 'Upskilling Program',
    programTypeAr: 'برنامج التطوير المهني',
    title: 'Regulatory Compliance & Anti-Money Laundering',
    titleAr: 'الامتثال التنظيمي ومكافحة غسل الأموال',
    provider: 'ADCCI in partnership with KPMG',
    providerAr: 'غرفة أبوظبي بالتعاون مع كي بي إم جي',
    sector: 'Legal & Compliance',
    sectorAr: 'القانون والامتثال',
    description: 'Comprehensive training on UAE AML/CFT regulations, sanctions screening, and compliance program design. Participants receive templates and checklists for immediate implementation.',
    descriptionAr: 'تدريب شامل على لوائح مكافحة غسل الأموال وتمويل الإرهاب في الإمارات وفحص العقوبات وتصميم برامج الامتثال.',
    duration: '2 days',
    durationAr: 'يومان',
    format: 'Hybrid',
    formatAr: 'مدمج',
    language: 'Bilingual',
    level: 'Intermediate',
    levelAr: 'متوسط',
    upcomingSessions: [
      { date: '2026-03-28', spotsAvailable: 2, location: 'ADCCI Training Center', locationAr: 'مركز تدريب الغرفة' },
      { date: '2026-05-15', spotsAvailable: 18, location: 'Virtual (Teams)', locationAr: 'افتراضي (تيمز)' },
    ],
    tags: ['AML', 'Compliance', 'Regulatory', 'Legal'],
    tagsAr: ['مكافحة غسل الأموال', 'الامتثال', 'التنظيمي', 'القانوني'],
    isFeatured: false,
    certificationOffered: true,
    targetAudience: 'Compliance officers, Legal teams, Risk managers',
    targetAudienceAr: 'مسؤولو الامتثال والفرق القانونية ومديرو المخاطر',
  },
  {
    id: 'ks-009',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'Cybersecurity Essentials for SMEs',
    titleAr: 'أساسيات الأمن السيبراني للمنشآت الصغيرة والمتوسطة',
    provider: 'ADCCI in partnership with DarkMatter',
    providerAr: 'غرفة أبوظبي بالتعاون مع دارك ماتر',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    description: 'Learn essential cybersecurity practices to protect your business from threats. Covers phishing prevention, data protection, incident response, and UAE NESA compliance requirements.',
    descriptionAr: 'تعلّم الممارسات الأساسية للأمن السيبراني لحماية أعمالك من التهديدات. يغطي منع التصيد وحماية البيانات والاستجابة للحوادث ومتطلبات الامتثال لهيئة الأمن الإلكتروني.',
    duration: '4 hours',
    durationAr: '4 ساعات',
    format: 'Online',
    formatAr: 'عبر الإنترنت',
    language: 'English',
    level: 'Beginner',
    levelAr: 'مبتدئ',
    upcomingSessions: [
      { date: '2026-03-12', spotsAvailable: 40, location: 'Virtual (Webinar)', locationAr: 'افتراضي (ندوة عبر الإنترنت)' },
      { date: '2026-04-16', spotsAvailable: 40, location: 'Virtual (Webinar)', locationAr: 'افتراضي (ندوة عبر الإنترنت)' },
    ],
    tags: ['Cybersecurity', 'Data Protection', 'NESA', 'Security'],
    tagsAr: ['الأمن السيبراني', 'حماية البيانات', 'الأمن الإلكتروني', 'الأمان'],
    isFeatured: false,
    certificationOffered: false,
    targetAudience: 'SME owners, IT managers, Business managers',
    targetAudienceAr: 'أصحاب المنشآت الصغيرة ومديرو تكنولوجيا المعلومات',
  },
  {
    id: 'ks-010',
    programType: 'Upskilling Program',
    programTypeAr: 'برنامج التطوير المهني',
    title: 'Project Management Professional (PMP) Prep',
    titleAr: 'الإعداد لشهادة إدارة المشاريع الاحترافية',
    provider: 'ADCCI in partnership with PMI UAE Chapter',
    providerAr: 'غرفة أبوظبي بالتعاون مع فرع معهد إدارة المشاريع الإمارات',
    sector: 'Operations',
    sectorAr: 'العمليات',
    description: 'Intensive PMP exam preparation covering PMBOK 7th edition, agile methodologies, and hybrid project management. Includes 35 contact hours required for exam eligibility.',
    descriptionAr: 'إعداد مكثف لامتحان PMP يغطي الدليل المعرفي السابع ومنهجيات أجايل وإدارة المشاريع الهجينة. يتضمن 35 ساعة تواصل مطلوبة للأهلية للامتحان.',
    duration: '5 days',
    durationAr: '5 أيام',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'English',
    level: 'Advanced',
    levelAr: 'متقدم',
    upcomingSessions: [
      { date: '2026-04-06', spotsAvailable: 10, location: 'ADCCI Training Center', locationAr: 'مركز تدريب الغرفة' },
      { date: '2026-06-22', spotsAvailable: 15, location: 'ADCCI Training Center', locationAr: 'مركز تدريب الغرفة' },
    ],
    tags: ['PMP', 'Project Management', 'Agile', 'Certification'],
    tagsAr: ['إدارة المشاريع', 'أجايل', 'شهادة مهنية', 'PMP'],
    isFeatured: true,
    certificationOffered: true,
    targetAudience: 'Project managers, Team leads, Operations professionals',
    targetAudienceAr: 'مديرو المشاريع وقادة الفرق ومتخصصو العمليات',
  },
  {
    id: 'ks-011',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'International Trade & Export Procedures',
    titleAr: 'التجارة الدولية وإجراءات التصدير',
    provider: 'ADCCI Trade Department',
    providerAr: 'قسم التجارة — غرفة أبوظبي',
    sector: 'Finance',
    sectorAr: 'المالية',
    description: 'Master the essentials of international trade documentation, Incoterms 2020, letters of credit, and certificate of origin procedures. Practical guidance on exporting from Abu Dhabi free zones.',
    descriptionAr: 'إتقان أساسيات وثائق التجارة الدولية ومصطلحات التجارة 2020 وخطابات الاعتماد وإجراءات شهادة المنشأ. إرشادات عملية حول التصدير من المناطق الحرة في أبوظبي.',
    duration: '3 hours',
    durationAr: '3 ساعات',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'Arabic',
    level: 'Beginner',
    levelAr: 'مبتدئ',
    upcomingSessions: [
      { date: '2026-03-20', spotsAvailable: 30, location: 'ADCCI Auditorium', locationAr: 'قاعة الغرفة' },
      { date: '2026-05-25', spotsAvailable: 30, location: 'ADCCI Auditorium', locationAr: 'قاعة الغرفة' },
    ],
    tags: ['Trade', 'Export', 'Incoterms', 'Documentation'],
    tagsAr: ['التجارة', 'التصدير', 'مصطلحات التجارة', 'التوثيق'],
    isFeatured: false,
    certificationOffered: false,
    targetAudience: 'Exporters, Trade managers, Logistics coordinators',
    targetAudienceAr: 'المصدرون ومديرو التجارة ومنسقو الخدمات اللوجستية',
  },
  {
    id: 'ks-012',
    programType: 'Upskilling Program',
    programTypeAr: 'برنامج التطوير المهني',
    title: 'Data Analytics & Business Intelligence',
    titleAr: 'تحليل البيانات وذكاء الأعمال',
    provider: 'ADCCI in partnership with Microsoft',
    providerAr: 'غرفة أبوظبي بالتعاون مع مايكروسوفت',
    sector: 'Technology',
    sectorAr: 'التكنولوجيا',
    description: 'Learn to transform raw data into actionable insights using Power BI, Excel advanced analytics, and basic Python for data science. Includes hands-on projects with real UAE market data.',
    descriptionAr: 'تعلّم تحويل البيانات الخام إلى رؤى قابلة للتنفيذ باستخدام Power BI وتحليلات Excel المتقدمة وأساسيات Python لعلوم البيانات.',
    duration: '4 days',
    durationAr: '4 أيام',
    format: 'Hybrid',
    formatAr: 'مدمج',
    language: 'English',
    level: 'Intermediate',
    levelAr: 'متوسط',
    upcomingSessions: [
      { date: '2026-04-12', spotsAvailable: 12, location: 'ADCCI Innovation Hub', locationAr: 'مركز الابتكار — الغرفة' },
      { date: '2026-06-08', spotsAvailable: 20, location: 'ADCCI Innovation Hub + Virtual', locationAr: 'مركز الابتكار + افتراضي' },
    ],
    tags: ['Data Analytics', 'Power BI', 'Business Intelligence', 'Python'],
    tagsAr: ['تحليل البيانات', 'ذكاء الأعمال', 'بايثون', 'تصور البيانات'],
    isFeatured: false,
    certificationOffered: true,
    targetAudience: 'Analysts, Managers, Business professionals',
    targetAudienceAr: 'المحللون والمديرون ومتخصصو الأعمال',
  },
  {
    id: 'ks-013',
    programType: 'Knowledge Series',
    programTypeAr: 'سلسلة المعرفة',
    title: 'Contract Management & Dispute Resolution',
    titleAr: 'إدارة العقود وحل النزاعات',
    provider: 'ADCCI in partnership with Al Tamimi & Company',
    providerAr: 'غرفة أبوظبي بالتعاون مع التميمي وشركاه',
    sector: 'Legal & Compliance',
    sectorAr: 'القانون والامتثال',
    description: 'Understand UAE contract law fundamentals, negotiate better terms, and navigate dispute resolution mechanisms including ADCCAC arbitration. Practical templates and clause libraries included.',
    descriptionAr: 'فهم أساسيات قانون العقود الإماراتي والتفاوض على شروط أفضل والتنقل في آليات حل النزاعات بما في ذلك التحكيم لدى مركز أبوظبي للتحكيم التجاري.',
    duration: '2 days',
    durationAr: 'يومان',
    format: 'In-Person',
    formatAr: 'حضوري',
    language: 'Bilingual',
    level: 'Intermediate',
    levelAr: 'متوسط',
    upcomingSessions: [
      { date: '2026-04-22', spotsAvailable: 18, location: 'ADCCI HQ — Conference Room A', locationAr: 'مقر الغرفة — قاعة المؤتمرات أ' },
      { date: '2026-07-08', spotsAvailable: 18, location: 'ADCCI HQ — Conference Room A', locationAr: 'مقر الغرفة — قاعة المؤتمرات أ' },
    ],
    tags: ['Contracts', 'Legal', 'Arbitration', 'Dispute Resolution'],
    tagsAr: ['العقود', 'القانون', 'التحكيم', 'حل النزاعات'],
    isFeatured: false,
    certificationOffered: false,
    targetAudience: 'Legal teams, Procurement officers, Business owners',
    targetAudienceAr: 'الفرق القانونية ومسؤولو المشتريات وأصحاب الأعمال',
  },
]

export const sectorsAr: Record<string, string> = {
  'Finance': 'المالية',
  'Technology': 'التكنولوجيا',
  'Sustainability': 'الاستدامة',
  'Leadership': 'القيادة',
  'Legal & Compliance': 'القانون والامتثال',
  'Marketing': 'التسويق',
  'Operations': 'العمليات',
  'HR & People': 'الموارد البشرية',
}

export const sectorColors: Record<string, string> = {
  'Finance': 'bg-blue-100 dark:bg-blue-500/20 text-blue-800 dark:text-blue-300 border-blue-200 dark:border-blue-500/30',
  'Technology': 'bg-cyan-100 dark:bg-cyan-500/20 text-cyan-800 dark:text-cyan-300 border-cyan-200 dark:border-cyan-500/30',
  'Sustainability': 'bg-emerald-100 dark:bg-emerald-500/20 text-emerald-800 dark:text-emerald-300 border-emerald-200 dark:border-emerald-500/30',
  'Leadership': 'bg-purple-100 dark:bg-purple-500/20 text-purple-800 dark:text-purple-300 border-purple-200 dark:border-purple-500/30',
  'Legal & Compliance': 'bg-rose-100 dark:bg-rose-500/20 text-rose-800 dark:text-rose-300 border-rose-200 dark:border-rose-500/30',
  'Marketing': 'bg-pink-100 dark:bg-pink-500/20 text-pink-800 dark:text-pink-300 border-pink-200 dark:border-pink-500/30',
  'Operations': 'bg-amber-100 dark:bg-amber-500/20 text-amber-800 dark:text-amber-300 border-amber-200 dark:border-amber-500/30',
  'HR & People': 'bg-indigo-100 dark:bg-indigo-500/20 text-indigo-800 dark:text-indigo-300 border-indigo-200 dark:border-indigo-500/30',
}

export const formatColors: Record<string, string> = {
  'In-Person': 'bg-teal-100 dark:bg-teal-500/20 text-teal-800 dark:text-teal-300 border-teal-200 dark:border-teal-500/30',
  'Online': 'bg-sky-100 dark:bg-sky-500/20 text-sky-800 dark:text-sky-300 border-sky-200 dark:border-sky-500/30',
  'Hybrid': 'bg-violet-100 dark:bg-violet-500/20 text-violet-800 dark:text-violet-300 border-violet-200 dark:border-violet-500/30',
}

export const levelColors: Record<string, string> = {
  'Beginner': 'bg-green-100 dark:bg-green-500/20 text-green-800 dark:text-green-300 border-green-200 dark:border-green-500/30',
  'Intermediate': 'bg-yellow-100 dark:bg-yellow-500/20 text-yellow-800 dark:text-yellow-300 border-yellow-200 dark:border-yellow-500/30',
  'Advanced': 'bg-red-100 dark:bg-red-500/20 text-red-800 dark:text-red-300 border-red-200 dark:border-red-500/30',
}
