export { TopMetricsStatic } from './TopMetricsStatic'
export { TimeSeriesStatic } from './TimeSeriesStatic'
export { FunnelStatic } from './FunnelStatic'
export { ESGPanelStatic } from './ESGPanelStatic'
export { AIPanelStatic } from './AIPanelStatic'
export { RecentApplicationsTableStatic } from './RecentApplicationsTableStatic'
